In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn.metrics import r2_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.feature_selection import RFE
import warnings
warnings.filterwarnings("ignore")

In [2]:
election_data_path = '../../datasets/Clean Datasets/Electoral Data/'
census_data_path = '../../datasets/Clean Datasets/Census Data/'
master_data_path = '../../datasets/Clean Datasets/'

In [3]:
votes = pd.read_csv(election_data_path + 'Final_Vote_Count.csv')
data = pd.read_csv(master_data_path + 'CED to All Demographics and Results.csv')
ages = pd.read_csv(census_data_path + 'CED to Age (Individual years).csv')
master = pd.read_csv(master_data_path + 'CED to All Demographics and Results Norm.csv')

In [4]:
No_NA_master = master.dropna().reset_index()
No_NA_master

index       LGA  AGE5P - 0-4 years  AGE5P - 5-9 years  \
0        0  Adelaide           0.053945           0.050723   
1        1     Aston           0.058553           0.058845   
2        2  Ballarat           0.062608           0.066055   
3        3     Banks           0.060613           0.059368   
4        4    Barker           0.055697           0.063267   
..     ...       ...                ...                ...   
146    164   Werriwa           0.072655           0.078559   
147    165   Whitlam           0.060113           0.065839   
148    166  Wide Bay           0.048858           0.060062   
149    167     Wills           0.062568           0.052921   
150    168    Wright           0.060883           0.074120   

     AGE5P - 10-14 years  AGE5P - 15-19 years  AGE5P - 20-24 years  \
0               0.045462             0.057361             0.096777   
1               0.058346             0.064261             0.066246   
2               0.061419             0.062910             0.065860   
3               0.055980             0.060472             0.068598   
4               0.062771             0.059757             0.050169   
..                   ...                  ...                  ...   
146             0.077535             0.077236             0.072380   
147             0.064873             0.066358             0.055673   
148             0.064301             0.056468             0.042020   
149             0.043203             0.043616             0.080062   
150             0.075367             0.070010             0.055936   

     AGE5P - 25-29 years  AGE5P - 30-34 years  AGE5P - 35-39 years  ...  \
0               0.092626             0.088211             0.070221  ...   
1               0.064391             0.067479             0.066700  ...   
2               0.060216             0.059006             0.059537  ...   
3               0.074162             0.073559             0.066018  ...   
4               0.051558             0.054241             0.054597  ...   
..                   ...                  ...                  ...  ...   
146             0.065587             0.071789             0.070232  ...   
147             0.052804             0.056448             0.056678  ...   
148             0.040191             0.044199             0.049902  ...   
149             0.112030             0.108720             0.087122  ...   
150             0.051039             0.056818             0.061605  ...   

     RELP - Inadequately described  RELP - Not stated  SEXP - Male  \
0                         0.005066           0.089304     0.495587   
1                         0.005405           0.070051     0.488707   
2                         0.005846           0.089031     0.483762   
3                         0.002856           0.069741     0.486358   
4                         0.004301           0.092769     0.505114   
..                             ...                ...          ...   
146                       0.002762           0.083012     0.493321   
147                       0.003842           0.073615     0.485514   
148                       0.004758           0.104341     0.494793   
149                       0.006079           0.085782     0.489373   
150                       0.004098           0.097011     0.498322   

     SEXP - Female  MDCP - Married in a registered marriage  \
0         0.504413                                 0.302321   
1         0.511293                                 0.393949   
2         0.516238                                 0.323363   
3         0.513642                                 0.385881   
4         0.494886                                 0.359438   
..             ...                                      ...   
146       0.506679                                 0.358736   
147       0.514486                                 0.366147   
148       0.505207                                 0.350901   
149       0.510627                             

In [5]:
set(No_NA_master['PartyNm'])

{'Australian Labor Party',
 'Australian Labor Party (Northern Territory) Branch',
 'Centre Alliance',
 'Independent',
 "Katter's Australian Party (KAP)",
 'Labor',
 'Liberal',
 'Liberal National Party of Queensland',
 'The Greens (VIC)',
 'The Nationals'}

# 1) Adjusted Model partitioning into LNP, ALP, Other 

In [6]:
adjusted_master = No_NA_master.replace({ 'PartyNm' : {'Liberal' : 'LNP', 'Liberal National Party of Queensland' : 'LNP',
                                                      'The Nationals' : 'LNP', 'Labor' : 'ALP',
                                                      'Australian Labor Party' : 'ALP',
                                                     'Australian Labor Party (Northern Territory) Branch' : 'ALP',
                                                      'Centre Alliance' : 'Other', 'Independent' : 'Other', 
                                                      'Katter\'s Australian Party (KAP)' : 'Other',
                                                      'The Greens (VIC)' : 'Other'}})

adjusted_master

index       LGA  AGE5P - 0-4 years  AGE5P - 5-9 years  \
0        0  Adelaide           0.053945           0.050723   
1        1     Aston           0.058553           0.058845   
2        2  Ballarat           0.062608           0.066055   
3        3     Banks           0.060613           0.059368   
4        4    Barker           0.055697           0.063267   
..     ...       ...                ...                ...   
146    164   Werriwa           0.072655           0.078559   
147    165   Whitlam           0.060113           0.065839   
148    166  Wide Bay           0.048858           0.060062   
149    167     Wills           0.062568           0.052921   
150    168    Wright           0.060883           0.074120   

     AGE5P - 10-14 years  AGE5P - 15-19 years  AGE5P - 20-24 years  \
0               0.045462             0.057361             0.096777   
1               0.058346             0.064261             0.066246   
2               0.061419             0.062910             0.065860   
3               0.055980             0.060472             0.068598   
4               0.062771             0.059757             0.050169   
..                   ...                  ...                  ...   
146             0.077535             0.077236             0.072380   
147             0.064873             0.066358             0.055673   
148             0.064301             0.056468             0.042020   
149             0.043203             0.043616             0.080062   
150             0.075367             0.070010             0.055936   

     AGE5P - 25-29 years  AGE5P - 30-34 years  AGE5P - 35-39 years  ...  \
0               0.092626             0.088211             0.070221  ...   
1               0.064391             0.067479             0.066700  ...   
2               0.060216             0.059006             0.059537  ...   
3               0.074162             0.073559             0.066018  ...   
4               0.051558             0.054241             0.054597  ...   
..                   ...                  ...                  ...  ...   
146             0.065587             0.071789             0.070232  ...   
147             0.052804             0.056448             0.056678  ...   
148             0.040191             0.044199             0.049902  ...   
149             0.112030             0.108720             0.087122  ...   
150             0.051039             0.056818             0.061605  ...   

     RELP - Inadequately described  RELP - Not stated  SEXP - Male  \
0                         0.005066           0.089304     0.495587   
1                         0.005405           0.070051     0.488707   
2                         0.005846           0.089031     0.483762   
3                         0.002856           0.069741     0.486358   
4                         0.004301           0.092769     0.505114   
..                             ...                ...          ...   
146                       0.002762           0.083012     0.493321   
147                       0.003842           0.073615     0.485514   
148                       0.004758           0.104341     0.494793   
149                       0.006079           0.085782     0.489373   
150                       0.004098           0.097011     0.498322   

     SEXP - Female  MDCP - Married in a registered marriage  \
0         0.504413                                 0.302321   
1         0.511293                                 0.393949   
2         0.516238                                 0.323363   
3         0.513642                                 0.385881   
4         0.494886                                 0.359438   
..             ...                                      ...   
146       0.506679                                 0.358736   
147       0.514486                                 0.366147   
148       0.505207                                 0.350901   
149       0.510627                             

In [7]:
len(adjusted_master[adjusted_master['PartyNm'] == 'LNP'])

77

In [8]:
len(adjusted_master[adjusted_master['PartyNm'] == 'ALP'])

68

In [9]:
len(adjusted_master[adjusted_master['PartyNm'] == 'Other'])

6

# 2) Strength of victory model

Definitions by the AEC https://www.aec.gov.au/footer/glossary.htm#:~:text=Marginal%20seat,per%20cent%20of%20the%20vote.

- Marginal seat 56% or less
- Fairly safe seat 56-60%
- Safe seat 60% or greater

In [10]:
strength = No_NA_master[['LGA', 'PartyNm','PreferencePercent']]

In [11]:
Safe = strength[strength['PreferencePercent'] >= 60]
set(Safe['PartyNm'])

{'Australian Labor Party',
 'Independent',
 "Katter's Australian Party (KAP)",
 'Labor',
 'Liberal',
 'Liberal National Party of Queensland',
 'The Greens (VIC)',
 'The Nationals'}

In [12]:
strength[(strength['PreferencePercent'] < 60) & (strength['PreferencePercent'] > 56)]

LGA                               PartyNm  PreferencePercent
0           Adelaide                Australian Labor Party              58.18
3              Banks                               Liberal              56.26
5             Barton                                 Labor              59.41
7               Bean                Australian Labor Party              57.52
8            Bendigo                Australian Labor Party              59.04
9          Bennelong                               Liberal              56.91
13            Bonner  Liberal National Party of Queensland              57.41
18             Brand                Australian Labor Party              56.66
36            Cowper                         The Nationals              56.79
52             Flynn  Liberal National Party of Queensland              58.66
53             Forde  Liberal National Party of Queensland              58.60
58         Fremantle                Australian Labor Party              56.92
62         Goldstein                               Liberal              57.79
70           Herbert  Liberal National Party of Queensland              58.36
72         Hindmarsh                Australian Labor Party              56.54
74              Holt                Australian Labor Party              58.70
76            Hughes                               Liberal              59.85
80            Isaacs                Australian Labor Party              56.43
81          Jagajaga                Australian Labor Party              56.57
83   Kingsford Smith                                 Labor              58.81
95         Macarthur                                 Labor              58.40
97         Macnamara                Australian Labor Party              56.25
99             Makin                Australian Labor Party              59.72
105          McMahon                                 Labor              56.64
108          Menzies                               Liberal              57.53
110           Monash                               Liberal              57.36
117     North Sydney                               Liberal              59.27
119            Oxley                Australian Labor Party              56.39
120             Page                         The Nationals              59.45
124           Pearce                               Liberal              57.52
126           Petrie  Liberal National Party of Queensland              58.40
127           Rankin                Australian Labor Party              56.44
132             Ryan  Liberal National Party of Queensland              56.03
138            Sturt                               Liberal              56.87
143        Warringah                           Independent              57.24
149            Wills                Australian Labor Party              58.17

In [13]:
strength[strength['PreferencePercent'] <= 56]

LGA                                            PartyNm  \
6           Bass                                            Liberal   
11         Blair                             Australian Labor Party   
14       Boothby                                            Liberal   
16       Braddon                                            Liberal   
19      Brisbane               Liberal National Party of Queensland   
21          Burt                             Australian Labor Party   
27         Casey                                            Liberal   
29      Chisholm                                            Liberal   
33   Corangamite                             Australian Labor Party   
35         Cowan                             Australian Labor Party   
40        Deakin                                            Liberal   
41       Dickson               Liberal National Party of Queensland   
42        Dobell                                              Labor   
43       Dunkley                             Australian Labor Party   
45   Eden-Monaro                                              Labor   
51      Flinders                                            Liberal   
60       Gilmore                                              Labor   
65      Greenway                                              Labor   
67      Griffith                             Australian Labor Party   
69       Hasluck                                            Liberal   
71       Higgins                                            Liberal   
75        Hotham                             Australian Labor Party   
78        Hunter                                              Labor   
79          Indi                                        Independent   
85       Kooyong                                            Liberal   
86      La Trobe                                            Liberal   
88    Leichhardt               Liberal National Party of Queensland   
89        Lilley                             Australian Labor Party   
90       Lindsay                                            Liberal   
91      Lingiari  Australian Labor Party (Northern Territory) Br...   
92       Longman               Liberal National Party of Queensland   
94         Lyons                             Australian Labor Party   
98     Macquarie                                              Labor   
103         Mayo                                    Centre Alliance   
104       McEwen                             Australian Labor Party   
113      Moreton                             Australian Labor Party   
122   Parramatta                                              Labor   
123     Paterson                                              Labor   
125        Perth                             Australian Labor Party   
128         Reid                                            Liberal   
129     Richmond                                              Labor   
131    Robertson                                            Liberal   
134    Shortland                                              Labor   
135      Solomon  Australian Labor Party (Northern Territory) Br...   
137     Stirling                                            Liberal   
139         Swan                                            Liberal   
145    Wentworth                                            Liberal   
146      Werriwa                                              Labor   

     PreferencePercent  
6                50.41  
11               51.21  
14               51.38  
16               53.09  
19               54.92  
21               54.99  
27               54.64  
29               50.57  
33               51.07  
35               50.83  
40               54.78  
41               54.64  
42               51.50  
43               52.74  
45               50.85  
51               55.64  
60               52.61  
65               52.80  
67               52.86  
69               55.39  
71      

In [14]:
conditions = [(adjusted_master['PreferencePercent'] <= 56),
              ((adjusted_master['PreferencePercent'] > 56) & (adjusted_master['PreferencePercent'] < 60 )
              & (adjusted_master['PartyNm'] == 'LNP')),
              ((adjusted_master['PreferencePercent'] > 56) & (adjusted_master['PreferencePercent'] < 60 )
              & (adjusted_master['PartyNm'] == 'ALP')),
              (adjusted_master['PreferencePercent'] >= 60) & (adjusted_master['PartyNm'] == 'LNP'),
              (adjusted_master['PreferencePercent'] > 56) & (adjusted_master['PartyNm'] == 'ALP'),
             (adjusted_master['PreferencePercent'] > 56) & (adjusted_master['PartyNm'] == 'Other')]

strengths = ['Marginal', 'Fairly Safe LNP', 'Fairly Safe ALP', 'Safe LNP', 'Safe ALP', 'Other']

adjusted_master['Strength'] = np.select(conditions, strengths)
adjusted_master

index       LGA  AGE5P - 0-4 years  AGE5P - 5-9 years  \
0        0  Adelaide           0.053945           0.050723   
1        1     Aston           0.058553           0.058845   
2        2  Ballarat           0.062608           0.066055   
3        3     Banks           0.060613           0.059368   
4        4    Barker           0.055697           0.063267   
..     ...       ...                ...                ...   
146    164   Werriwa           0.072655           0.078559   
147    165   Whitlam           0.060113           0.065839   
148    166  Wide Bay           0.048858           0.060062   
149    167     Wills           0.062568           0.052921   
150    168    Wright           0.060883           0.074120   

     AGE5P - 10-14 years  AGE5P - 15-19 years  AGE5P - 20-24 years  \
0               0.045462             0.057361             0.096777   
1               0.058346             0.064261             0.066246   
2               0.061419             0.062910             0.065860   
3               0.055980             0.060472             0.068598   
4               0.062771             0.059757             0.050169   
..                   ...                  ...                  ...   
146             0.077535             0.077236             0.072380   
147             0.064873             0.066358             0.055673   
148             0.064301             0.056468             0.042020   
149             0.043203             0.043616             0.080062   
150             0.075367             0.070010             0.055936   

     AGE5P - 25-29 years  AGE5P - 30-34 years  AGE5P - 35-39 years  ...  \
0               0.092626             0.088211             0.070221  ...   
1               0.064391             0.067479             0.066700  ...   
2               0.060216             0.059006             0.059537  ...   
3               0.074162             0.073559             0.066018  ...   
4               0.051558             0.054241             0.054597  ...   
..                   ...                  ...                  ...  ...   
146             0.065587             0.071789             0.070232  ...   
147             0.052804             0.056448             0.056678  ...   
148             0.040191             0.044199             0.049902  ...   
149             0.112030             0.108720             0.087122  ...   
150             0.051039             0.056818             0.061605  ...   

     RELP - Not stated  SEXP - Male  SEXP - Female  \
0             0.089304     0.495587       0.504413   
1             0.070051     0.488707       0.511293   
2             0.089031     0.483762       0.516238   
3             0.069741     0.486358       0.513642   
4             0.092769     0.505114       0.494886   
..                 ...          ...            ...   
146           0.083012     0.493321       0.506679   
147           0.073615     0.485514       0.514486   
148           0.104341     0.494793       0.505207   
149           0.085782     0.489373       0.510627   
150           0.097011     0.498322       0.501678   

     MDCP - Married in a registered marriage  \
0                                   0.302321   
1                                   0.393949   
2                                   0.323363   
3                                   0.385881   
4                                   0.359438   
..                                       ...   
146                                 0.358736   
147                                 0.366147   
148                                 0.350901   
149                                 0.304067   
150                                 0.362536   

     MDCP - Married in a de facto marriage  MDCP - Not married  \
0                                 0.073786            0.364082   
1                                 0.060754            0.305368   
2                                 0.081842            0.301819   
3                           

In [15]:
set(adjusted_master['Strength'])

{'Fairly Safe ALP',
 'Fairly Safe LNP',
 'Marginal',
 'Other',
 'Safe ALP',
 'Safe LNP'}

# 3) Correct Model (ALP, LNP, Other)

Forgot non-ordinal categorical vars can't be regressed on a single output, need dummy vars & regress on those. 

created dummy variables:
- is_ALP
- is_LNP
- is_Other

In [16]:
adjusted_master['is_ALP'] = np.where(adjusted_master['PartyNm'] == 'ALP', 1, 0)
adjusted_master['is_LNP'] = np.where(adjusted_master['PartyNm'] == 'LNP', 1, 0)
adjusted_master['is_Other'] = np.where(adjusted_master['PartyNm'] == 'Other', 1, 0)
adjusted_master

index       LGA  AGE5P - 0-4 years  AGE5P - 5-9 years  \
0        0  Adelaide           0.053945           0.050723   
1        1     Aston           0.058553           0.058845   
2        2  Ballarat           0.062608           0.066055   
3        3     Banks           0.060613           0.059368   
4        4    Barker           0.055697           0.063267   
..     ...       ...                ...                ...   
146    164   Werriwa           0.072655           0.078559   
147    165   Whitlam           0.060113           0.065839   
148    166  Wide Bay           0.048858           0.060062   
149    167     Wills           0.062568           0.052921   
150    168    Wright           0.060883           0.074120   

     AGE5P - 10-14 years  AGE5P - 15-19 years  AGE5P - 20-24 years  \
0               0.045462             0.057361             0.096777   
1               0.058346             0.064261             0.066246   
2               0.061419             0.062910             0.065860   
3               0.055980             0.060472             0.068598   
4               0.062771             0.059757             0.050169   
..                   ...                  ...                  ...   
146             0.077535             0.077236             0.072380   
147             0.064873             0.066358             0.055673   
148             0.064301             0.056468             0.042020   
149             0.043203             0.043616             0.080062   
150             0.075367             0.070010             0.055936   

     AGE5P - 25-29 years  AGE5P - 30-34 years  AGE5P - 35-39 years  ...  \
0               0.092626             0.088211             0.070221  ...   
1               0.064391             0.067479             0.066700  ...   
2               0.060216             0.059006             0.059537  ...   
3               0.074162             0.073559             0.066018  ...   
4               0.051558             0.054241             0.054597  ...   
..                   ...                  ...                  ...  ...   
146             0.065587             0.071789             0.070232  ...   
147             0.052804             0.056448             0.056678  ...   
148             0.040191             0.044199             0.049902  ...   
149             0.112030             0.108720             0.087122  ...   
150             0.051039             0.056818             0.061605  ...   

     MDCP - Married in a registered marriage  \
0                                   0.302321   
1                                   0.393949   
2                                   0.323363   
3                                   0.385881   
4                                   0.359438   
..                                       ...   
146                                 0.358736   
147                                 0.366147   
148                                 0.350901   
149                                 0.304067   
150                                 0.362536   

     MDCP - Married in a de facto marriage  MDCP - Not married  \
0                                 0.073786            0.364082   
1                                 0.060754            0.305368   
2                                 0.081842            0.301819   
3                                 0.044820            0.335227   
4                                 0.078180            0.273848   
..                                     ...                 ...   
146                               0.039473            0.313827   
147                               0.067582            0.294500   
148                               0.080181            0.284154   
149                               0.093583            0.361030   
150                               0.081549            0.253436   

     MDCP - Not applicable  PreferencePercent  PartyNm         Strength  \
0                 0.259811              58.18      ALP  Fairly Safe ALP  

# 3.1 ALP model

In [42]:
train, test = train_test_split(adjusted_master, test_size=0.2, random_state=142)
print(train.shape)
print(test.shape)

(120, 146)
(31, 146)


In [43]:
X_train = train.drop(['index', 'LGA','PartyNm', 'PreferencePercent', 'Strength', 'is_ALP', 'is_LNP', 'is_Other'], axis=1)
y_train = train['is_ALP']
X_test = test.drop(['index', 'LGA','PartyNm', 'PreferencePercent', 'Strength', 'is_ALP', 'is_LNP', 'is_Other'], axis=1)
y_test = test['is_ALP']

In [44]:
model = LogisticRegression()
model.fit(X_train, y_train)
y_hat_train = model.predict(X_train)
y_hat_test = model.predict(X_test)
print("Accuracy score on training set: ", accuracy_score(y_train, y_hat_train))
print("Accuracy score on testing set: ", accuracy_score(y_test, y_hat_test))

Accuracy score on training set:  0.7416666666666667
Accuracy score on testing set:  0.6129032258064516


In [45]:
acc_scores = []
for i in range(1,140):
    clf = LogisticRegression()
    rfe = RFE(estimator=clf, n_features_to_select=i)
    
    rfe.fit(X_train, y_train)
    
    y_pred = rfe.predict(X_test)
    acc_score = accuracy_score(y_test, y_pred)
    
    print("Accuracy on test set using", i, "features: ", acc_score)
    
    acc_scores.append(acc_score)

best = acc_scores[0]
best_number_of_columns = 0;
for i in range(len(acc_scores)):
    if acc_scores[i] > best:
        best = acc_scores[i]
        best_number_of_columns = i
        
print(best_number_of_columns + 1, 'columns provide the highest accuracy at: %.2f' % (best*100), "%")

Accuracy on test set using 1 features:  0.5483870967741935
Accuracy on test set using 2 features:  0.5483870967741935
Accuracy on test set using 3 features:  0.6129032258064516
Accuracy on test set using 4 features:  0.5483870967741935
Accuracy on test set using 5 features:  0.5806451612903226
Accuracy on test set using 6 features:  0.6129032258064516
Accuracy on test set using 7 features:  0.6129032258064516
Accuracy on test set using 8 features:  0.6129032258064516
Accuracy on test set using 9 features:  0.5806451612903226
Accuracy on test set using 10 features:  0.5483870967741935
Accuracy on test set using 11 features:  0.5483870967741935
Accuracy on test set using 12 features:  0.5483870967741935
Accuracy on test set using 13 features:  0.5483870967741935
Accuracy on test set using 14 features:  0.5483870967741935
Accuracy on test set using 15 features:  0.6129032258064516
Accuracy on test set using 16 features:  0.6129032258064516
Accuracy on test set using 17 features:  0.612903

In [46]:
lr_model = LogisticRegression()
rfe = RFE(estimator=lr_model, n_features_to_select=3, step=1)
rfe.fit(X_train, y_train)
y_test_hat = rfe.predict(X_test)
print("accuracy score on test set: ", accuracy_score(y_test, y_test_hat))

accuracy score on test set:  0.6129032258064516


In [47]:
relevant_cols = []
for i in range(X_train.shape[1]):
    print('Column: %d, Selected %s, Rank: %.3f' % (i, rfe.support_[i], rfe.ranking_[i]))
    if rfe.support_[i] == True:
        relevant_cols.append(i)
        
print(relevant_cols)

Column: 0, Selected False, Rank: 26.000
Column: 1, Selected False, Rank: 123.000
Column: 2, Selected False, Rank: 56.000
Column: 3, Selected False, Rank: 87.000
Column: 4, Selected False, Rank: 15.000
Column: 5, Selected False, Rank: 7.000
Column: 6, Selected False, Rank: 6.000
Column: 7, Selected False, Rank: 22.000
Column: 8, Selected False, Rank: 82.000
Column: 9, Selected False, Rank: 68.000
Column: 10, Selected False, Rank: 39.000
Column: 11, Selected False, Rank: 31.000
Column: 12, Selected False, Rank: 25.000
Column: 13, Selected False, Rank: 18.000
Column: 14, Selected False, Rank: 21.000
Column: 15, Selected False, Rank: 32.000
Column: 16, Selected False, Rank: 53.000
Column: 17, Selected False, Rank: 61.000
Column: 18, Selected False, Rank: 79.000
Column: 19, Selected False, Rank: 107.000
Column: 20, Selected False, Rank: 134.000
Column: 21, Selected False, Rank: 71.000
Column: 22, Selected False, Rank: 112.000
Column: 23, Selected False, Rank: 75.000
Column: 24, Selected Fal

In [48]:
print("Columns that provide the best are:", relevant_cols)
result = pd.DataFrame(test['is_ALP'])
result.columns = ["Actual"]
result.insert(1, "Predicted", rfe.predict(X_test))
result.insert(2, "Pref Percent", test['PreferencePercent'].values)
display(result)

Columns that provide the best are: [86, 124, 126]


Actual  Predicted  Pref Percent
3         0          0         56.26
70        0          0         58.36
92        0          0         53.28
124       0          0         57.52
56        1          0         62.21
134       1          0         54.45
107       0          1         71.83
78        1          0         52.98
128       0          0         53.18
65        1          0         52.80
42        1          0         51.50
123       1          0         55.04
111       0          0         65.36
0         1          1         58.18
136       1          0         64.13
98        1          0         50.19
90        0          0         55.04
114       0          0         64.36
108       0          0         57.53
131       0          0         54.24
101       0          0         72.49
68        0          0         70.48
95        1          0         58.40
119       1          0         56.39
64        1          1         66.30
77        0          0         62.99
71        0          0         53.88
150       0          0         64.58
7         1          0         57.52
103       0          0         55.14
53        0          0         58.60

In [49]:
best_cols = X_test.iloc[:,relevant_cols]
best_cols

MSTP - Never married  RELP - Christianity  RELP - Islam
3                0.260373             0.555461      0.048503
70               0.331367             0.584734      0.005375
92               0.257813             0.561709      0.001849
124              0.265419             0.502974      0.011615
56               0.255628             0.492437      0.002484
134              0.250313             0.619925      0.001979
107              0.591751             0.260394      0.035241
78               0.260744             0.632586      0.002672
128              0.319403             0.457105      0.027582
65               0.233375             0.527592      0.048839
42               0.261646             0.624938      0.003161
123              0.254980             0.641047      0.002615
111              0.333886             0.508566      0.008611
0                0.357867             0.430949      0.042542
136              0.301677             0.456894      0.024514
98               0.264001             0.584620      0.002772
90               0.286019             0.632425      0.019091
114              0.265708             0.664317      0.004786
108              0.239032             0.512021      0.018006
131              0.255435             0.598827      0.003382
101              0.241290             0.679945      0.001313
68               0.255309             0.671598      0.010641
95               0.274782             0.609142      0.063042
119              0.276051             0.504791      0.026523
64               0.393886             0.398269      0.011578
77               0.243119             0.687635      0.006187
71               0.369329             0.424266      0.009518
150              0.248191             0.588464      0.003963
7                0.267665             0.513521      0.018860
103              0.227454             0.464238      0.001088
53               0.276851             0.550102      0.012473

In [50]:
list_name = best_cols.columns
list_name

Index(['MSTP - Never married', 'RELP - Christianity', 'RELP - Islam'], dtype='object')

In [51]:
coefficient_DF = pd.DataFrame(list(map(np.ravel, rfe.estimator_.coef_)), columns=X_train.columns[rfe.support_], index=rfe.estimator_.classes_)
coefficient_DF

MSTP - Never married  RELP - Christianity  RELP - Islam
0               0.67747            -1.245888      1.028113
1               0.67747            -1.245888      1.028113

# 3.1 Interpretation (is_ALP) (61%)

The main determinants of whether an electorate is votes ALP or not, is:
- The proprtion of people who are Christian (significantly negatively affects it)
- The proprtion of people who are Muslim (significantly positively affects it)
- The proprtion of people who have never married (Slightly positively affects it)

# Number of seats ALP Win

In [53]:
print("Columns that provide the best are:", relevant_cols)
result = pd.DataFrame(adjusted_master['is_ALP'])
result.columns = ["Actual"]
result.insert(1, "Predicted", rfe.predict(adjusted_master.drop(['index', 'LGA','PartyNm', 'PreferencePercent',
                                                                'Strength', 'is_ALP', 'is_LNP', 'is_Other'], axis=1)))
result.insert(2, "Pref Percent", adjusted_master['PreferencePercent'].values)
result.insert(3, "Electorate", adjusted_master['LGA'].values)
display(result)

print('Number of seats the ALP win:',result['Predicted'].sum())

Columns that provide the best are: [86, 124, 126]


Actual  Predicted  Pref Percent Electorate
0         1          1         58.18   Adelaide
1         0          0         60.13      Aston
2         1          0         60.98   Ballarat
3         0          0         56.26      Banks
4         0          0         68.94     Barker
..      ...        ...           ...        ...
146       1          0         55.47    Werriwa
147       1          0         60.91    Whitlam
148       0          0         63.15   Wide Bay
149       1          1         58.17      Wills
150       0          0         64.58     Wright

[151 rows x 4 columns]

Number of seats the ALP win: 16


In [54]:
ALP_Wins = result[result['Predicted'] == 1]
ALP_Wins['Electorate']

0        Adelaide
12       Blaxland
19       Brisbane
20          Bruce
23        Calwell
24       Canberra
32         Cooper
64      Grayndler
97      Macnamara
107     Melbourne
122    Parramatta
139          Swan
140        Sydney
144        Watson
145     Wentworth
149         Wills
Name: Electorate, dtype: object

# 3.2 is_LNP model

In [55]:
train, test = train_test_split(adjusted_master, test_size=0.2, random_state=142)
print(train.shape)
print(test.shape)

(120, 146)
(31, 146)


In [56]:
X_train = train.drop(['index', 'LGA','PartyNm', 'PreferencePercent', 'Strength', 'is_ALP', 'is_LNP', 'is_Other'], axis=1)
y_train = train['is_LNP']
X_test = test.drop(['index', 'LGA','PartyNm', 'PreferencePercent', 'Strength', 'is_ALP', 'is_LNP', 'is_Other'], axis=1)
y_test = test['is_LNP']

In [57]:
model = LogisticRegression()
model.fit(X_train, y_train)
y_hat_train = model.predict(X_train)
y_hat_test = model.predict(X_test)
print("Accuracy score on training set: ", accuracy_score(y_train, y_hat_train))
print("Accuracy score on testing set: ", accuracy_score(y_test, y_hat_test))

Accuracy score on training set:  0.725
Accuracy score on testing set:  0.6451612903225806


In [58]:
acc_scores = []
for i in range(1,140):
    clf = LogisticRegression()
    rfe = RFE(estimator=clf, n_features_to_select=i)
    
    rfe.fit(X_train, y_train)
    
    y_pred = rfe.predict(X_test)
    acc_score = accuracy_score(y_test, y_pred)
    
    print("Accuracy on test set using", i, "features: ", acc_score)
    
    acc_scores.append(acc_score)

best = acc_scores[0]
best_number_of_columns = 0;
for i in range(len(acc_scores)):
    if acc_scores[i] > best:
        best = acc_scores[i]
        best_number_of_columns = i
        
print(best_number_of_columns + 1, 'columns provide the highest accuracy at: %.2f' % (best*100), "%")

Accuracy on test set using 1 features:  0.6129032258064516
Accuracy on test set using 2 features:  0.6129032258064516
Accuracy on test set using 3 features:  0.5806451612903226
Accuracy on test set using 4 features:  0.5483870967741935
Accuracy on test set using 5 features:  0.5483870967741935
Accuracy on test set using 6 features:  0.5483870967741935
Accuracy on test set using 7 features:  0.5806451612903226
Accuracy on test set using 8 features:  0.5806451612903226
Accuracy on test set using 9 features:  0.5806451612903226
Accuracy on test set using 10 features:  0.5806451612903226
Accuracy on test set using 11 features:  0.5806451612903226
Accuracy on test set using 12 features:  0.5806451612903226
Accuracy on test set using 13 features:  0.5806451612903226
Accuracy on test set using 14 features:  0.5483870967741935
Accuracy on test set using 15 features:  0.5483870967741935
Accuracy on test set using 16 features:  0.5806451612903226
Accuracy on test set using 17 features:  0.548387

In [59]:
lr_model = LogisticRegression()
rfe = RFE(estimator=lr_model, n_features_to_select=47, step=1)
rfe.fit(X_train, y_train)
y_test_hat = rfe.predict(X_test)
print("accuracy score on test set: ", accuracy_score(y_test, y_test_hat))

accuracy score on test set:  0.6451612903225806


In [60]:
relevant_cols = []
for i in range(X_train.shape[1]):
    print('Column: %d, Selected %s, Rank: %.3f' % (i, rfe.support_[i], rfe.ranking_[i]))
    if rfe.support_[i] == True:
        relevant_cols.append(i)
        
print(relevant_cols)

Column: 0, Selected True, Rank: 1.000
Column: 1, Selected False, Rank: 66.000
Column: 2, Selected False, Rank: 11.000
Column: 3, Selected False, Rank: 33.000
Column: 4, Selected True, Rank: 1.000
Column: 5, Selected True, Rank: 1.000
Column: 6, Selected True, Rank: 1.000
Column: 7, Selected True, Rank: 1.000
Column: 8, Selected False, Rank: 31.000
Column: 9, Selected False, Rank: 22.000
Column: 10, Selected True, Rank: 1.000
Column: 11, Selected True, Rank: 1.000
Column: 12, Selected True, Rank: 1.000
Column: 13, Selected True, Rank: 1.000
Column: 14, Selected True, Rank: 1.000
Column: 15, Selected True, Rank: 1.000
Column: 16, Selected False, Rank: 6.000
Column: 17, Selected False, Rank: 15.000
Column: 18, Selected False, Rank: 32.000
Column: 19, Selected False, Rank: 63.000
Column: 20, Selected False, Rank: 89.000
Column: 21, Selected False, Rank: 17.000
Column: 22, Selected False, Rank: 80.000
Column: 23, Selected False, Rank: 40.000
Column: 24, Selected False, Rank: 49.000
Column: 

In [61]:
print("Columns that provide the best are:", relevant_cols)
result = pd.DataFrame(test['is_LNP'])
result.columns = ["Actual"]
result.insert(1, "Predicted", rfe.predict(X_test))
result.insert(2, "Pref Percent", test['PreferencePercent'].values)
display(result)

Columns that provide the best are: [0, 4, 5, 6, 7, 10, 11, 12, 13, 14, 15, 25, 28, 31, 38, 39, 46, 47, 51, 61, 66, 69, 71, 72, 77, 79, 80, 83, 86, 87, 90, 91, 92, 97, 106, 118, 119, 122, 123, 124, 125, 126, 128, 129, 134, 136, 137]


Actual  Predicted  Pref Percent
3         1          1         56.26
70        1          0         58.36
92        1          1         53.28
124       1          1         57.52
56        0          1         62.21
134       0          1         54.45
107       0          0         71.83
78        0          1         52.98
128       1          0         53.18
65        0          0         52.80
42        0          1         51.50
123       0          1         55.04
111       1          0         65.36
0         0          0         58.18
136       0          0         64.13
98        0          1         50.19
90        1          1         55.04
114       1          1         64.36
108       1          1         57.53
131       1          1         54.24
101       1          1         72.49
68        1          1         70.48
95        0          0         58.40
119       0          0         56.39
64        0          0         66.30
77        1          1         62.99
71        1          0         53.88
150       1          1         64.58
7         0          0         57.52
103       0          1         55.14
53        1          1         58.60

In [62]:
best_cols = X_test.iloc[:,relevant_cols]
best_cols

AGE5P - 0-4 years  AGE5P - 20-24 years  AGE5P - 25-29 years  \
3             0.060613             0.068598             0.074162   
70            0.070830             0.086721             0.078522   
92            0.064828             0.062505             0.060643   
124           0.079176             0.064734             0.076436   
56            0.059398             0.048807             0.050483   
134           0.058333             0.055385             0.050907   
107           0.037696             0.172723             0.182719   
78            0.065358             0.058623             0.059331   
128           0.058885             0.087894             0.114632   
65            0.080754             0.060545             0.070088   
42            0.061068             0.057914             0.053981   
123           0.066469             0.058206             0.060506   
111           0.047779             0.079635             0.083584   
0             0.053945             0.096777             0.092626   
136           0.077451             0.074264             0.074316   
98            0.058913             0.056665             0.052444   
90            0.075389             0.070922             0.077221   
114           0.060304             0.057865             0.055206   
108           0.048672             0.062423             0.053251   
131           0.056376             0.052379             0.051526   
101           0.064005             0.051565             0.054532   
68            0.065174             0.065147             0.063749   
95            0.076859             0.071686             0.074341   
119           0.079105             0.070275             0.072878   
64            0.060788             0.067757             0.099278   
77            0.066998             0.057346             0.058003   
71            0.049081             0.087459             0.107743   
150           0.060883             0.055936             0.051039   
7             0.066758             0.060364             0.065045   
103           0.054343             0.047168             0.041547   
53            0.076394             0.067321             0.069272   

     AGE5P - 30-34 years  AGE5P - 35-39 years  AGE5P - 50-54 years  \
3               0.073559             0.066018             0.068046   
70              0.074623             0.064649             0.061693   
92              0.060699             0.058862             0.063701   
124             0.078890             0.070544             0.063458   
56              0.059065             0.058893             0.067738   
134             0.056568             0.055316             0.066985   
107             0.135079             0.078709             0.039943   
78              0.061920             0.058527             0.064810   
128             0.106807             0.079441             0.059232   
65              0.088415             0.091308             0.058728   
42              0.057499             0.057849             0.064800   
123             0.061059             0.058502             0.064503   
111             0.075363             0.065382             0.064568   
0               0.088211             0.070221             0.059555   
136             0.073817             0.061461             0.066454   
98              0.053738             0.057365             0.071490   
90              0.079455             0.072369             0.059632   
114             0.054720             0.052054             0.065784   
108             0.051724             0.056815             0.073088   
131             0.053357             0.056537             0.069430   
101             0.054961             0.053795             0.068748   
68              0.062601             0.057469             0.061627   
95              0.078908             0.070113             0.062311   
119             0.079895             0.074038             0.062115   
64              0.102576             0.091848             0.065062   
77      

In [63]:
list_name = best_cols.columns
list_name

Index(['AGE5P - 0-4 years', 'AGE5P - 20-24 years', 'AGE5P - 25-29 years',
       'AGE5P - 30-34 years', 'AGE5P - 35-39 years', 'AGE5P - 50-54 years',
       'AGE5P - 55-59 years', 'AGE5P - 60-64 years', 'AGE5P - 65-69 years',
       'AGE5P - 70-74 years', 'AGE5P - 75-79 years',
       'HEAP - Certificate III & IV Level',
       'HEAP - Secondary Education - Years 9 and below',
       'HEAP - Not applicable', 'INCP - $2,000-$2,999 ($104,000-$155,999)',
       'INCP - $3,000 or more ($156,000 or more)', 'INCP - Nil income',
       'INCP - Not applicable', 'INDP - Agriculture, Forestry and Fishing',
       'INDP - Mining', 'INDP - Public Administration and Safety',
       'INDP - Transport, Postal and Warehousing',
       'LFHRP - Employed, worked full-time',
       'LFHRP - Employed, worked part-time', 'LFHRP - Not in the labour force',
       'LFHRP - Not applicable', 'GNGP - National Government',
       'GNGP - Private sector', 'MSTP - Never married', 'MSTP - Widowed',
       'MSTP - M

In [64]:
coefficient_DF = pd.DataFrame(list(map(np.ravel, rfe.estimator_.coef_)), columns=X_train.columns[rfe.support_], index=rfe.estimator_.classes_)
coefficient_DF

AGE5P - 0-4 years  AGE5P - 20-24 years  AGE5P - 25-29 years  \
0           -0.19152            -0.250676               -0.393   
1           -0.19152            -0.250676               -0.393   

   AGE5P - 30-34 years  AGE5P - 35-39 years  AGE5P - 50-54 years  \
0            -0.401863            -0.228084             0.119506   
1            -0.401863            -0.228084             0.119506   

   AGE5P - 55-59 years  AGE5P - 60-64 years  AGE5P - 65-69 years  \
0             0.156255             0.192222             0.246282   
1             0.156255             0.192222             0.246282   

   AGE5P - 70-74 years  ...  RLHP - Not applicable  RELP - Buddhism  \
0             0.227102  ...               0.203385        -0.395329   
1             0.227102  ...               0.203385        -0.395329   

   RELP - Christianity  RELP - Hinduism  RELP - Islam  RELP - Other Religions  \
0             1.152395        -0.303826     -0.865314               -0.152802   
1             1.152395        -0.303826     -0.865314               -0.152802   

   RELP - Secular Beliefs and Other Spiritual Beliefs and No Religious Affiliation  \
0                                           0.493993                                 
1                                           0.493993                                 

   MDCP - Married in a registered marriage  MDCP - Not married  \
0                                 0.414232           -0.561112   
1                                 0.414232           -0.561112   

   MDCP - Not applicable  
0                0.14731  
1                0.14731  

[2 rows x 47 columns]

In [65]:
coefficient_DF.iloc[0]

AGE5P - 0-4 years                                                                 -0.191520
AGE5P - 20-24 years                                                               -0.250676
AGE5P - 25-29 years                                                               -0.393000
AGE5P - 30-34 years                                                               -0.401863
AGE5P - 35-39 years                                                               -0.228084
AGE5P - 50-54 years                                                                0.119506
AGE5P - 55-59 years                                                                0.156255
AGE5P - 60-64 years                                                                0.192222
AGE5P - 65-69 years                                                                0.246282
AGE5P - 70-74 years                                                                0.227102
AGE5P - 75-79 years                                                             

# 3.2 Interpretation (is_LNP) (65%)

## Significant Positive Influence
- Christian (1.152395) 
- Married (0.519304)
- Secular Beliefs and Other Spiritual Beliefs and No Religious Affiliation (0.493993)
- registered marriage (0.414232)
- Husband, Wife or Partner in a registered marriage (0.392106)

## Significant Negative Influence
- Islam (-0.865314)
- Never married (-0.618718)
- Not married (-0.561112)
- 30-34 years (-0.401863)
- Buddhism (-0.395329)
- 25-29 years (-0.393000)

# Number of Seats LNP Win

In [69]:
print("Columns that provide the best are:", relevant_cols)
result = pd.DataFrame(adjusted_master['is_LNP'])
result.columns = ["Actual"]
result.insert(1, "Predicted", rfe.predict(adjusted_master.drop(['index', 'LGA','PartyNm', 'PreferencePercent',
                                                                'Strength', 'is_ALP', 'is_LNP', 'is_Other'], axis=1)))
result.insert(2, "Pref Percent", adjusted_master['PreferencePercent'].values)
result.insert(3, "Electorate", adjusted_master['LGA'].values)
display(result)

print('Number of seats the LNP win:',result['Predicted'].sum())

Columns that provide the best are: [0, 4, 5, 6, 7, 10, 11, 12, 13, 14, 15, 25, 28, 31, 38, 39, 46, 47, 51, 61, 66, 69, 71, 72, 77, 79, 80, 83, 86, 87, 90, 91, 92, 97, 106, 118, 119, 122, 123, 124, 125, 126, 128, 129, 134, 136, 137]


Actual  Predicted  Pref Percent Electorate
0         0          0         58.18   Adelaide
1         1          1         60.13      Aston
2         0          1         60.98   Ballarat
3         1          1         56.26      Banks
4         1          1         68.94     Barker
..      ...        ...           ...        ...
146       0          0         55.47    Werriwa
147       0          1         60.91    Whitlam
148       1          1         63.15   Wide Bay
149       0          0         58.17      Wills
150       1          1         64.58     Wright

[151 rows x 4 columns]

Number of seats the LNP win: 98


In [70]:
LNP_Wins = result[result['Predicted'] == 1]
LNP_Wins['Electorate']

1          Aston
2       Ballarat
3          Banks
4         Barker
6           Bass
         ...    
142       Wannon
143    Warringah
147      Whitlam
148     Wide Bay
150       Wright
Name: Electorate, Length: 98, dtype: object

# 3.3 is_Other Model

In [71]:
train, test = train_test_split(adjusted_master, test_size=0.2, random_state=142)
print(train.shape)
print(test.shape)

(120, 146)
(31, 146)


In [72]:
X_train = train.drop(['index', 'LGA','PartyNm', 'PreferencePercent', 'Strength', 'is_ALP', 'is_LNP', 'is_Other'], axis=1)
y_train = train['is_Other']
X_test = test.drop(['index', 'LGA','PartyNm', 'PreferencePercent', 'Strength', 'is_ALP', 'is_LNP', 'is_Other'], axis=1)
y_test = test['is_Other']

In [73]:
model = LogisticRegression()
model.fit(X_train, y_train)
y_hat_train = model.predict(X_train)
y_hat_test = model.predict(X_test)
print("Accuracy score on training set: ", accuracy_score(y_train, y_hat_train))
print("Accuracy score on testing set: ", accuracy_score(y_test, y_hat_test))

Accuracy score on training set:  0.9666666666666667
Accuracy score on testing set:  0.9354838709677419


In [74]:
acc_scores = []
for i in range(1,140):
    clf = LogisticRegression()
    rfe = RFE(estimator=clf, n_features_to_select=i)
    
    rfe.fit(X_train, y_train)
    
    y_pred = rfe.predict(X_test)
    acc_score = accuracy_score(y_test, y_pred)
    
    print("Accuracy on test set using", i, "features: ", acc_score)
    
    acc_scores.append(acc_score)

best = acc_scores[0]
best_number_of_columns = 0;
for i in range(len(acc_scores)):
    if acc_scores[i] > best:
        best = acc_scores[i]
        best_number_of_columns = i
        
print(best_number_of_columns + 1, 'columns provide the highest accuracy at: %.2f' % (best*100), "%")

Accuracy on test set using 1 features:  0.9354838709677419
Accuracy on test set using 2 features:  0.9354838709677419
Accuracy on test set using 3 features:  0.9354838709677419
Accuracy on test set using 4 features:  0.9354838709677419
Accuracy on test set using 5 features:  0.9354838709677419
Accuracy on test set using 6 features:  0.9354838709677419
Accuracy on test set using 7 features:  0.9354838709677419
Accuracy on test set using 8 features:  0.9354838709677419
Accuracy on test set using 9 features:  0.9354838709677419
Accuracy on test set using 10 features:  0.9354838709677419
Accuracy on test set using 11 features:  0.9354838709677419
Accuracy on test set using 12 features:  0.9354838709677419
Accuracy on test set using 13 features:  0.9354838709677419
Accuracy on test set using 14 features:  0.9354838709677419
Accuracy on test set using 15 features:  0.9354838709677419
Accuracy on test set using 16 features:  0.9354838709677419
Accuracy on test set using 17 features:  0.935483

In [75]:
lr_model = LogisticRegression()
rfe = RFE(estimator=lr_model, n_features_to_select=1, step=1)
rfe.fit(X_train, y_train)
y_test_hat = rfe.predict(X_test)
print("accuracy score on test set: ", accuracy_score(y_test, y_test_hat))

accuracy score on test set:  0.9354838709677419


In [76]:
relevant_cols = []
for i in range(X_train.shape[1]):
    print('Column: %d, Selected %s, Rank: %.3f' % (i, rfe.support_[i], rfe.ranking_[i]))
    if rfe.support_[i] == True:
        relevant_cols.append(i)
        
print(relevant_cols)

Column: 0, Selected False, Rank: 47.000
Column: 1, Selected False, Rank: 93.000
Column: 2, Selected False, Rank: 74.000
Column: 3, Selected False, Rank: 66.000
Column: 4, Selected False, Rank: 18.000
Column: 5, Selected False, Rank: 21.000
Column: 6, Selected False, Rank: 23.000
Column: 7, Selected False, Rank: 42.000
Column: 8, Selected False, Rank: 108.000
Column: 9, Selected False, Rank: 80.000
Column: 10, Selected False, Rank: 53.000
Column: 11, Selected False, Rank: 33.000
Column: 12, Selected False, Rank: 35.000
Column: 13, Selected False, Rank: 34.000
Column: 14, Selected False, Rank: 36.000
Column: 15, Selected False, Rank: 63.000
Column: 16, Selected False, Rank: 81.000
Column: 17, Selected False, Rank: 85.000
Column: 18, Selected False, Rank: 109.000
Column: 19, Selected False, Rank: 130.000
Column: 20, Selected False, Rank: 133.000
Column: 21, Selected False, Rank: 55.000
Column: 22, Selected False, Rank: 76.000
Column: 23, Selected False, Rank: 41.000
Column: 24, Selected F

In [77]:
print("Columns that provide the best are:", relevant_cols)
result = pd.DataFrame(test['is_Other'])
result.columns = ["Actual"]
result.insert(1, "Predicted", rfe.predict(X_test))
result.insert(2, "Pref Percent", test['PreferencePercent'].values)
display(result)

Columns that provide the best are: [129]


Actual  Predicted  Pref Percent
3         0          0         56.26
70        0          0         58.36
92        0          0         53.28
124       0          0         57.52
56        0          0         62.21
134       0          0         54.45
107       1          0         71.83
78        0          0         52.98
128       0          0         53.18
65        0          0         52.80
42        0          0         51.50
123       0          0         55.04
111       0          0         65.36
0         0          0         58.18
136       0          0         64.13
98        0          0         50.19
90        0          0         55.04
114       0          0         64.36
108       0          0         57.53
131       0          0         54.24
101       0          0         72.49
68        0          0         70.48
95        0          0         58.40
119       0          0         56.39
64        0          0         66.30
77        0          0         62.99
71        0          0         53.88
150       0          0         64.58
7         0          0         57.52
103       1          0         55.14
53        0          0         58.60

In [78]:
best_cols = X_test.iloc[:,relevant_cols]
best_cols

RELP - Secular Beliefs and Other Spiritual Beliefs and No Religious Affiliation
3                                             0.242016                              
70                                            0.290817                              
92                                            0.318683                              
124                                           0.342444                              
56                                            0.400382                              
134                                           0.293455                              
107                                           0.472482                              
78                                            0.260657                              
128                                           0.285639                              
65                                            0.156307                              
42                                            0.271944                              
123                                           0.257929                              
111                                           0.321620                              
0                                             0.339837                              
136                                           0.375639                              
98                                            0.310298                              
90                                            0.222032                              
114                                           0.212013                              
108                                           0.335852                              
131                                           0.294278                              
101                                           0.200118                              
68                                            0.205241                              
95                                            0.184146                              
119                                           0.274726                              
64                                            0.415847                              
77                                            0.213552                              
71                                            0.365632                              
150                                           0.288079                              
7                                             0.335144                              
103                                           0.423214                              
53                                            0.316483

In [79]:
coefficient_DF = pd.DataFrame(list(map(np.ravel, rfe.estimator_.coef_)), columns=X_train.columns[rfe.support_], index=rfe.estimator_.classes_)
coefficient_DF

RELP - Secular Beliefs and Other Spiritual Beliefs and No Religious Affiliation
0                                             0.1457                              
1                                             0.1457

# 3.3 Interpretation is_Other (Caution) (94%)

Though The model says it a high accuracy at 93%, this is a misguided interpretation as for all outputs it is outputing 0, i.e. not other. Hence this model can't predict whether an electorate is not ALP/LNP. The highest coefficient is (0.1457) it is very weak which explains why the model can't accurately predict a seat that is 'Other'. I would contend that the reasons why this Logistic regression model can't predict 'Other' electorates is due to there not being enough of them in order to correctly train the model, the total dataset has only 7 data points, also within the 'Other' category I have a group of party's like the Greens with Katters' Australian Party, Greens' have left-wing policies, KAP have Right-wing, I would doubt the composition of these electorates are similar.   

# Number of seats Other wins

In [82]:
print("Columns that provide the best are:", relevant_cols)
result = pd.DataFrame(adjusted_master['is_LNP'])
result.columns = ["Actual"]
result.insert(1, "Predicted", rfe.predict(adjusted_master.drop(['index', 'LGA','PartyNm', 'PreferencePercent',
                                                                'Strength', 'is_ALP', 'is_LNP', 'is_Other'], axis=1)))
result.insert(2, "Pref Percent", adjusted_master['PreferencePercent'].values)
result.insert(3, "Electorate", adjusted_master['LGA'].values)
display(result)

print('Number of seats the Other win:',result['Predicted'].sum())

Columns that provide the best are: [129]


Actual  Predicted  Pref Percent Electorate
0         0          0         58.18   Adelaide
1         1          0         60.13      Aston
2         0          0         60.98   Ballarat
3         1          0         56.26      Banks
4         1          0         68.94     Barker
..      ...        ...           ...        ...
146       0          0         55.47    Werriwa
147       0          0         60.91    Whitlam
148       1          0         63.15   Wide Bay
149       0          0         58.17      Wills
150       1          0         64.58     Wright

[151 rows x 4 columns]

Number of seats the Other win: 0


In [81]:
Other_Wins = result[result['Predicted'] == 1]
Other_Wins['Electorate']

Series([], Name: Electorate, dtype: object)

# 4 More Specific model (Safe seats)

In [58]:
adjusted_master

index       LGA  AGE5P - 0-4 years  AGE5P - 5-9 years  \
0        0  Adelaide           0.053945           0.050723   
1        1     Aston           0.058553           0.058845   
2        2  Ballarat           0.062608           0.066055   
3        3     Banks           0.060613           0.059368   
4        4    Barker           0.055697           0.063267   
..     ...       ...                ...                ...   
146    164   Werriwa           0.072655           0.078559   
147    165   Whitlam           0.060113           0.065839   
148    166  Wide Bay           0.048858           0.060062   
149    167     Wills           0.062568           0.052921   
150    168    Wright           0.060883           0.074120   

     AGE5P - 10-14 years  AGE5P - 15-19 years  AGE5P - 20-24 years  \
0               0.045462             0.057361             0.096777   
1               0.058346             0.064261             0.066246   
2               0.061419             0.062910             0.065860   
3               0.055980             0.060472             0.068598   
4               0.062771             0.059757             0.050169   
..                   ...                  ...                  ...   
146             0.077535             0.077236             0.072380   
147             0.064873             0.066358             0.055673   
148             0.064301             0.056468             0.042020   
149             0.043203             0.043616             0.080062   
150             0.075367             0.070010             0.055936   

     AGE5P - 25-29 years  AGE5P - 30-34 years  AGE5P - 35-39 years  ...  \
0               0.092626             0.088211             0.070221  ...   
1               0.064391             0.067479             0.066700  ...   
2               0.060216             0.059006             0.059537  ...   
3               0.074162             0.073559             0.066018  ...   
4               0.051558             0.054241             0.054597  ...   
..                   ...                  ...                  ...  ...   
146             0.065587             0.071789             0.070232  ...   
147             0.052804             0.056448             0.056678  ...   
148             0.040191             0.044199             0.049902  ...   
149             0.112030             0.108720             0.087122  ...   
150             0.051039             0.056818             0.061605  ...   

     MDCP - Married in a registered marriage  \
0                                   0.302321   
1                                   0.393949   
2                                   0.323363   
3                                   0.385881   
4                                   0.359438   
..                                       ...   
146                                 0.358736   
147                                 0.366147   
148                                 0.350901   
149                                 0.304067   
150                                 0.362536   

     MDCP - Married in a de facto marriage  MDCP - Not married  \
0                                 0.073786            0.364082   
1                                 0.060754            0.305368   
2                                 0.081842            0.301819   
3                                 0.044820            0.335227   
4                                 0.078180            0.273848   
..                                     ...                 ...   
146                               0.039473            0.313827   
147                               0.067582            0.294500   
148                               0.080181            0.284154   
149                               0.093583            0.361030   
150                               0.081549            0.253436   

     MDCP - Not applicable  PreferencePercent  PartyNm         Strength  \
0                 0.259811              58.18      ALP  Fairly Safe ALP  

In [59]:
adjusted_master['is_Marginal'] = np.where(adjusted_master['Strength'] == 'Marginal', 1, 0)
adjusted_master['is_Fairly_Safe_ALP'] = np.where(adjusted_master['Strength'] == 'Fairly Safe ALP', 1, 0)
adjusted_master['is_Fairly_Safe_LNP'] = np.where(adjusted_master['Strength'] == 'Fairly Safe LNP', 1, 0)
adjusted_master['is_Safe_ALP'] = np.where(adjusted_master['Strength'] == 'Safe ALP', 1, 0)
adjusted_master['is_Safe_LNP'] = np.where(adjusted_master['Strength'] == 'Safe LNP', 1, 0)
adjusted_master['is_Strength_Other'] = np.where(adjusted_master['Strength'] == 'Other', 1, 0)
adjusted_master

index       LGA  AGE5P - 0-4 years  AGE5P - 5-9 years  \
0        0  Adelaide           0.053945           0.050723   
1        1     Aston           0.058553           0.058845   
2        2  Ballarat           0.062608           0.066055   
3        3     Banks           0.060613           0.059368   
4        4    Barker           0.055697           0.063267   
..     ...       ...                ...                ...   
146    164   Werriwa           0.072655           0.078559   
147    165   Whitlam           0.060113           0.065839   
148    166  Wide Bay           0.048858           0.060062   
149    167     Wills           0.062568           0.052921   
150    168    Wright           0.060883           0.074120   

     AGE5P - 10-14 years  AGE5P - 15-19 years  AGE5P - 20-24 years  \
0               0.045462             0.057361             0.096777   
1               0.058346             0.064261             0.066246   
2               0.061419             0.062910             0.065860   
3               0.055980             0.060472             0.068598   
4               0.062771             0.059757             0.050169   
..                   ...                  ...                  ...   
146             0.077535             0.077236             0.072380   
147             0.064873             0.066358             0.055673   
148             0.064301             0.056468             0.042020   
149             0.043203             0.043616             0.080062   
150             0.075367             0.070010             0.055936   

     AGE5P - 25-29 years  AGE5P - 30-34 years  AGE5P - 35-39 years  ...  \
0               0.092626             0.088211             0.070221  ...   
1               0.064391             0.067479             0.066700  ...   
2               0.060216             0.059006             0.059537  ...   
3               0.074162             0.073559             0.066018  ...   
4               0.051558             0.054241             0.054597  ...   
..                   ...                  ...                  ...  ...   
146             0.065587             0.071789             0.070232  ...   
147             0.052804             0.056448             0.056678  ...   
148             0.040191             0.044199             0.049902  ...   
149             0.112030             0.108720             0.087122  ...   
150             0.051039             0.056818             0.061605  ...   

            Strength  is_ALP  is_LNP  is_Other  is_Marginal  \
0    Fairly Safe ALP       1       0         0            0   
1           Safe LNP       0       1         0            0   
2           Safe ALP       1       0         0            0   
3    Fairly Safe LNP       0       1         0            0   
4           Safe LNP       0       1         0            0   
..               ...     ...     ...       ...          ...   
146         Marginal       1       0         0            1   
147         Safe ALP       1       0         0            0   
148         Safe LNP       0       1         0            0   
149  Fairly Safe ALP       1       0         0            0   
150         Safe LNP       0       1         0            0   

     is_Fairly_Safe_ALP  is_Fairly_Safe_LNP  is_Safe_ALP  is_Safe_LNP  \
0                     1                   0            0            0   
1                     0                   0            0            1   
2                     0                   0            1            0   
3                     0                   1            0            0   
4                     0                   0            0            1   
..                  ...                 ...          ...          ...   
146                   0                   0            0            0   
147                   0                   0            1            0   
148                   0                   0            0            1   
149                   1        

# 4.1 Marginal Model

In [145]:
train, test = train_test_split(adjusted_master, test_size=0.2, random_state=142)
print(train.shape)
print(test.shape)

(120, 152)
(31, 152)


In [146]:
X_train = train.drop(['index', 'LGA','PartyNm', 'PreferencePercent', 'Strength', 'is_ALP', 'is_LNP', 'is_Other', 'is_Marginal',
                     'is_Fairly_Safe_ALP', 'is_Fairly_Safe_LNP', 'is_Safe_ALP', 'is_Safe_LNP', 'is_Strength_Other'], axis=1)
y_train = train['is_Marginal']
X_test = test.drop(['index', 'LGA','PartyNm', 'PreferencePercent', 'Strength', 'is_ALP', 'is_LNP', 'is_Other', 'is_Marginal',
                     'is_Fairly_Safe_ALP', 'is_Fairly_Safe_LNP', 'is_Safe_ALP', 'is_Safe_LNP', 'is_Strength_Other'], axis=1)
y_test = test['is_Marginal']

In [147]:
model = LogisticRegression()
model.fit(X_train, y_train)
y_hat_train = model.predict(X_train)
y_hat_test = model.predict(X_test)
print("Accuracy score on training set: ", accuracy_score(y_train, y_hat_train))
print("Accuracy score on testing set: ", accuracy_score(y_test, y_hat_test))

Accuracy score on training set:  0.7
Accuracy score on testing set:  0.6129032258064516


In [148]:
acc_scores = []
for i in range(1,140):
    clf = LogisticRegression()
    rfe = RFE(estimator=clf, n_features_to_select=i)
    
    rfe.fit(X_train, y_train)
    
    y_pred = rfe.predict(X_test)
    acc_score = accuracy_score(y_test, y_pred)
    
    print("Accuracy on test set using", i, "features: ", acc_score)
    
    acc_scores.append(acc_score)

best = acc_scores[0]
best_number_of_columns = 0;
for i in range(len(acc_scores)):
    if acc_scores[i] > best:
        best = acc_scores[i]
        best_number_of_columns = i
        
print(best_number_of_columns + 1, 'columns provide the highest accuracy at: %.2f' % (best*100), "%")

Accuracy on test set using 1 features:  0.6129032258064516
Accuracy on test set using 2 features:  0.6129032258064516
Accuracy on test set using 3 features:  0.6129032258064516
Accuracy on test set using 4 features:  0.6129032258064516
Accuracy on test set using 5 features:  0.6129032258064516
Accuracy on test set using 6 features:  0.6129032258064516
Accuracy on test set using 7 features:  0.6129032258064516
Accuracy on test set using 8 features:  0.6129032258064516
Accuracy on test set using 9 features:  0.6129032258064516
Accuracy on test set using 10 features:  0.6129032258064516
Accuracy on test set using 11 features:  0.6129032258064516
Accuracy on test set using 12 features:  0.6129032258064516
Accuracy on test set using 13 features:  0.6129032258064516
Accuracy on test set using 14 features:  0.6129032258064516
Accuracy on test set using 15 features:  0.6129032258064516
Accuracy on test set using 16 features:  0.6129032258064516
Accuracy on test set using 17 features:  0.612903

In [149]:
lr_model = LogisticRegression()
rfe = RFE(estimator=lr_model, n_features_to_select=10, step=1)
rfe.fit(X_train, y_train)
y_test_hat = rfe.predict(X_test)
print("accuracy score on test set: ", accuracy_score(y_test, y_test_hat))

accuracy score on test set:  0.6129032258064516


In [150]:
relevant_cols = []
for i in range(X_train.shape[1]):
    print('Column: %d, Selected %s, Rank: %.3f' % (i, rfe.support_[i], rfe.ranking_[i]))
    if rfe.support_[i] == True:
        relevant_cols.append(i)
        
print(relevant_cols)

Column: 0, Selected False, Rank: 94.000
Column: 1, Selected False, Rank: 67.000
Column: 2, Selected False, Rank: 81.000
Column: 3, Selected False, Rank: 95.000
Column: 4, Selected False, Rank: 45.000
Column: 5, Selected False, Rank: 16.000
Column: 6, Selected False, Rank: 13.000
Column: 7, Selected False, Rank: 71.000
Column: 8, Selected False, Rank: 87.000
Column: 9, Selected False, Rank: 86.000
Column: 10, Selected False, Rank: 77.000
Column: 11, Selected False, Rank: 68.000
Column: 12, Selected False, Rank: 84.000
Column: 13, Selected False, Rank: 62.000
Column: 14, Selected False, Rank: 50.000
Column: 15, Selected False, Rank: 41.000
Column: 16, Selected False, Rank: 46.000
Column: 17, Selected False, Rank: 70.000
Column: 18, Selected False, Rank: 90.000
Column: 19, Selected False, Rank: 123.000
Column: 20, Selected False, Rank: 128.000
Column: 21, Selected False, Rank: 44.000
Column: 22, Selected False, Rank: 42.000
Column: 23, Selected False, Rank: 11.000
Column: 24, Selected Fal

In [151]:
print("Columns that provide the best are:", relevant_cols)
result = pd.DataFrame(test['is_Marginal'])
result.columns = ["Actual"]
result.insert(1, "Predicted", rfe.predict(X_test))
result.insert(2, "Pref Percent", test['PreferencePercent'].values)
display(result)

Columns that provide the best are: [62, 77, 85, 86, 90, 92, 124, 126, 129, 134]


Actual  Predicted  Pref Percent
3         0          0         56.26
70        0          0         58.36
92        1          0         53.28
124       0          0         57.52
56        0          0         62.21
134       1          0         54.45
107       0          0         71.83
78        1          0         52.98
128       1          0         53.18
65        1          0         52.80
42        1          0         51.50
123       1          0         55.04
111       0          0         65.36
0         0          0         58.18
136       0          0         64.13
98        1          0         50.19
90        1          0         55.04
114       0          0         64.36
108       0          0         57.53
131       1          0         54.24
101       0          0         72.49
68        0          0         70.48
95        0          0         58.40
119       0          0         56.39
64        0          0         66.30
77        0          0         62.99
71        1          0         53.88
150       0          0         64.58
7         0          0         57.52
103       1          0         55.14
53        0          0         58.60

In [77]:
best_cols = X_test.iloc[:,relevant_cols]
best_cols

INDP - Not applicable  LFHRP - Not in the labour force  \
3                 0.533226                         0.289307   
70                0.542880                         0.227649   
92                0.589752                         0.291475   
124               0.535209                         0.207218   
56                0.559708                         0.308677   
134               0.570357                         0.318004   
107               0.487229                         0.260181   
78                0.583925                         0.305707   
128               0.504883                         0.267467   
65                0.517665                         0.225184   
42                0.578397                         0.300408   
123               0.585717                         0.300010   
111               0.529888                         0.268097   
0                 0.541928                         0.298165   
136               0.618929                         0.301413   
98                0.518041                         0.262153   
90                0.523120                         0.235585   
114               0.582145                         0.292108   
108               0.529046                         0.296752   
131               0.560608                         0.308422   
101               0.571550                         0.275261   
68                0.553191                         0.259107   
95                0.544683                         0.245754   
119               0.559690                         0.240377   
64                0.448564                         0.199592   
77                0.517483                         0.239159   
71                0.474949                         0.242123   
150               0.548397                         0.250237   
7                 0.487342                         0.228712   
103               0.550468                         0.297215   
53                0.549980                         0.237681   

     GNGP - Not applicable  MSTP - Never married  MSTP - Married  \
3                 0.533239              0.260373        0.429529   
70                0.542897              0.331367        0.325917   
92                0.589748              0.257813        0.381666   
124               0.535174              0.265419        0.391204   
56                0.559928              0.255628        0.398361   
134               0.570325              0.250313        0.402176   
107               0.487512              0.591751        0.232039   
78                0.583959              0.260744        0.387295   
128               0.504869              0.319403        0.422374   
65                0.517650              0.233375        0.438427   
42                0.578400              0.261646        0.365818   
123               0.585721              0.254980        0.385849   
111               0.529809              0.333886        0.345265   
0                 0.541961              0.357867        0.351498   
136               0.616273              0.301677        0.325648   
98                0.518074              0.264001        0.398419   
90                0.523170              0.286019        0.366740   
114               0.582161              0.265708        0.382280   
108               0.529303              0.239032        0.478775   
131               0.560608              0.255435        0.391441   
101               0.571539              0.241290        0.403993   
68                0.553165              0.255309        0.397141   
95                0.544760              0.274782        0.379364   
119               0.559459              0.276051        0.373822   
64                0.448558              0.393886        0.326897   
77                0.517462              0.243119        0.415495   
71                0.474799              0.369329        0.373453   
150               0.548425              0.248191        0.410307   
7               

In [78]:
coefficient_DF = pd.DataFrame(list(map(np.ravel, rfe.estimator_.coef_)), columns=X_train.columns[rfe.support_], index=rfe.estimator_.classes_)
coefficient_DF

INDP - Not applicable  LFHRP - Not in the labour force  \
0              -0.211056                        -0.232745   
1              -0.211056                        -0.232745   

   GNGP - Not applicable  MSTP - Never married  MSTP - Married  \
0              -0.205949              0.218063       -0.169172   
1              -0.205949              0.218063       -0.169172   

   RLHP - Husband, Wife or Partner in a registered marriage  \
0                                           -0.20466          
1                                           -0.20466          

   RELP - Christianity  RELP - Islam  \
0            -0.637355     -0.205417   
1            -0.637355     -0.205417   

   RELP - Secular Beliefs and Other Spiritual Beliefs and No Religious Affiliation  \
0                                           0.617044                                 
1                                           0.617044                                 

   MDCP - Married in a registered marriage  
0                                -0.197312  
1                                -0.197312

# 4.1 Interpretation of Marginal seats (61% Accurate)


## Strongest determinants
- Secular Beliefs and Other Spiritual Beliefs and No Religious Affiliation (0.617044)
- Christianity (-0.637355)

## Weaker determinants
- Not in the labour force (-0.232745)
- Never married (0.218063)
- INDP - Not applicable (-0.211056)
- GNGP - Not applicable (-0.205949)
- Islam (-0.205417)
- Husband, Wife or Partner in a registered marriage (-0.20466)

# 4.2 Fairly Safe ALP Model

In [87]:
train, test = train_test_split(adjusted_master, test_size=0.2, random_state=142)
print(train.shape)
print(test.shape)

(120, 152)
(31, 152)


In [88]:
X_train = train.drop(['index', 'LGA','PartyNm', 'PreferencePercent', 'Strength', 'is_ALP', 'is_LNP', 'is_Other', 'is_Marginal',
                     'is_Fairly_Safe_ALP', 'is_Fairly_Safe_LNP', 'is_Safe_ALP', 'is_Safe_LNP', 'is_Strength_Other'], axis=1)
y_train = train['is_Fairly_Safe_ALP']
X_test = test.drop(['index', 'LGA','PartyNm', 'PreferencePercent', 'Strength', 'is_ALP', 'is_LNP', 'is_Other', 'is_Marginal',
                     'is_Fairly_Safe_ALP', 'is_Fairly_Safe_LNP', 'is_Safe_ALP', 'is_Safe_LNP', 'is_Strength_Other'], axis=1)
y_test = test['is_Fairly_Safe_ALP']

In [89]:
model = LogisticRegression()
model.fit(X_train, y_train)
y_hat_train = model.predict(X_train)
y_hat_test = model.predict(X_test)
print("Accuracy score on training set: ", accuracy_score(y_train, y_hat_train))
print("Accuracy score on testing set: ", accuracy_score(y_test, y_hat_test))

Accuracy score on training set:  0.8833333333333333
Accuracy score on testing set:  0.8709677419354839


In [90]:
acc_scores = []
for i in range(1,140):
    clf = LogisticRegression()
    rfe = RFE(estimator=clf, n_features_to_select=i)
    
    rfe.fit(X_train, y_train)
    
    y_pred = rfe.predict(X_test)
    acc_score = accuracy_score(y_test, y_pred)
    
    print("Accuracy on test set using", i, "features: ", acc_score)
    
    acc_scores.append(acc_score)

best = acc_scores[0]
best_number_of_columns = 0;
for i in range(len(acc_scores)):
    if acc_scores[i] > best:
        best = acc_scores[i]
        best_number_of_columns = i
        
print(best_number_of_columns + 1, 'columns provide the highest accuracy at: %.2f' % (best*100), "%")

Accuracy on test set using 1 features:  0.8709677419354839
Accuracy on test set using 2 features:  0.8709677419354839
Accuracy on test set using 3 features:  0.8709677419354839
Accuracy on test set using 4 features:  0.8709677419354839
Accuracy on test set using 5 features:  0.8709677419354839
Accuracy on test set using 6 features:  0.8709677419354839
Accuracy on test set using 7 features:  0.8709677419354839
Accuracy on test set using 8 features:  0.8709677419354839
Accuracy on test set using 9 features:  0.8709677419354839
Accuracy on test set using 10 features:  0.8709677419354839
Accuracy on test set using 11 features:  0.8709677419354839
Accuracy on test set using 12 features:  0.8709677419354839
Accuracy on test set using 13 features:  0.8709677419354839
Accuracy on test set using 14 features:  0.8709677419354839
Accuracy on test set using 15 features:  0.8709677419354839
Accuracy on test set using 16 features:  0.8709677419354839
Accuracy on test set using 17 features:  0.870967

In [91]:
lr_model = LogisticRegression()
rfe = RFE(estimator=lr_model, n_features_to_select=5, step=1)
rfe.fit(X_train, y_train)
y_test_hat = rfe.predict(X_test)
print("accuracy score on test set: ", accuracy_score(y_test, y_test_hat))

accuracy score on test set:  0.8709677419354839


In [92]:
relevant_cols = []
for i in range(X_train.shape[1]):
    print('Column: %d, Selected %s, Rank: %.3f' % (i, rfe.support_[i], rfe.ranking_[i]))
    if rfe.support_[i] == True:
        relevant_cols.append(i)
        
print(relevant_cols)

Column: 0, Selected False, Rank: 36.000
Column: 1, Selected False, Rank: 87.000
Column: 2, Selected False, Rank: 33.000
Column: 3, Selected False, Rank: 50.000
Column: 4, Selected False, Rank: 26.000
Column: 5, Selected False, Rank: 8.000
Column: 6, Selected False, Rank: 7.000
Column: 7, Selected False, Rank: 11.000
Column: 8, Selected False, Rank: 60.000
Column: 9, Selected False, Rank: 95.000
Column: 10, Selected False, Rank: 45.000
Column: 11, Selected False, Rank: 27.000
Column: 12, Selected False, Rank: 17.000
Column: 13, Selected False, Rank: 15.000
Column: 14, Selected False, Rank: 24.000
Column: 15, Selected False, Rank: 44.000
Column: 16, Selected False, Rank: 72.000
Column: 17, Selected False, Rank: 94.000
Column: 18, Selected False, Rank: 105.000
Column: 19, Selected False, Rank: 114.000
Column: 20, Selected False, Rank: 127.000
Column: 21, Selected False, Rank: 34.000
Column: 22, Selected False, Rank: 99.000
Column: 23, Selected False, Rank: 12.000
Column: 24, Selected Fals

In [95]:
print("Columns that provide the best are:", relevant_cols)
result = pd.DataFrame(test['is_ALP'])
result.columns = ["Actual"]
result.insert(1, "Predicted", rfe.predict(X_test))
result.insert(2, "Pref Percent", test['PreferencePercent'].values)
display(result)

Columns that provide the best are: [83, 86, 124, 126, 136]


Actual  Predicted  Pref Percent
3         0          0         56.26
70        0          0         58.36
92        0          0         53.28
124       0          0         57.52
56        1          0         62.21
134       1          0         54.45
107       0          0         71.83
78        1          0         52.98
128       0          0         53.18
65        1          0         52.80
42        1          0         51.50
123       1          0         55.04
111       0          0         65.36
0         1          0         58.18
136       1          0         64.13
98        1          0         50.19
90        0          0         55.04
114       0          0         64.36
108       0          0         57.53
131       0          0         54.24
101       0          0         72.49
68        0          0         70.48
95        1          0         58.40
119       1          0         56.39
64        1          0         66.30
77        0          0         62.99
71        0          0         53.88
150       0          0         64.58
7         1          0         57.52
103       0          0         55.14
53        0          0         58.60

In [96]:
coefficient_DF = pd.DataFrame(list(map(np.ravel, rfe.estimator_.coef_)), columns=X_train.columns[rfe.support_], index=rfe.estimator_.classes_)
coefficient_DF

GNGP - Private sector  MSTP - Never married  RELP - Christianity  \
0               0.189134              0.275993            -0.424978   
1               0.189134              0.275993            -0.424978   

   RELP - Islam  MDCP - Not married  
0      0.198243            0.220149  
1      0.198243            0.220149

# 4.2) Fairly Safe ALP Interpretation (87% Accurate)

## Strongest determinant
- Christianity (-0.424978)

## Weaker determinants
- Never married (0.275993)
- Not married (0.220149)
- Islam (0.198243)
- Private sector (0.189134)

# 4.3) Fairly Safe LNP

In [97]:
train, test = train_test_split(adjusted_master, test_size=0.2, random_state=142)
print(train.shape)
print(test.shape)

(120, 152)
(31, 152)


In [98]:
X_train = train.drop(['index', 'LGA','PartyNm', 'PreferencePercent', 'Strength', 'is_ALP', 'is_LNP', 'is_Other', 'is_Marginal',
                     'is_Fairly_Safe_ALP', 'is_Fairly_Safe_LNP', 'is_Safe_ALP', 'is_Safe_LNP', 'is_Strength_Other'], axis=1)
y_train = train['is_Fairly_Safe_LNP']
X_test = test.drop(['index', 'LGA','PartyNm', 'PreferencePercent', 'Strength', 'is_ALP', 'is_LNP', 'is_Other', 'is_Marginal',
                     'is_Fairly_Safe_ALP', 'is_Fairly_Safe_LNP', 'is_Safe_ALP', 'is_Safe_LNP', 'is_Strength_Other'], axis=1)
y_test = test['is_Fairly_Safe_LNP']

In [99]:
model = LogisticRegression()
model.fit(X_train, y_train)
y_hat_train = model.predict(X_train)
y_hat_test = model.predict(X_test)
print("Accuracy score on training set: ", accuracy_score(y_train, y_hat_train))
print("Accuracy score on testing set: ", accuracy_score(y_test, y_hat_test))

Accuracy score on training set:  0.9
Accuracy score on testing set:  0.8387096774193549


In [100]:
acc_scores = []
for i in range(1,140):
    clf = LogisticRegression()
    rfe = RFE(estimator=clf, n_features_to_select=i)
    
    rfe.fit(X_train, y_train)
    
    y_pred = rfe.predict(X_test)
    acc_score = accuracy_score(y_test, y_pred)
    
    print("Accuracy on test set using", i, "features: ", acc_score)
    
    acc_scores.append(acc_score)

best = acc_scores[0]
best_number_of_columns = 0;
for i in range(len(acc_scores)):
    if acc_scores[i] > best:
        best = acc_scores[i]
        best_number_of_columns = i
        
print(best_number_of_columns + 1, 'columns provide the highest accuracy at: %.2f' % (best*100), "%")

Accuracy on test set using 1 features:  0.8387096774193549
Accuracy on test set using 2 features:  0.8387096774193549
Accuracy on test set using 3 features:  0.8387096774193549
Accuracy on test set using 4 features:  0.8387096774193549
Accuracy on test set using 5 features:  0.8387096774193549
Accuracy on test set using 6 features:  0.8387096774193549
Accuracy on test set using 7 features:  0.8387096774193549
Accuracy on test set using 8 features:  0.8387096774193549
Accuracy on test set using 9 features:  0.8387096774193549
Accuracy on test set using 10 features:  0.8387096774193549
Accuracy on test set using 11 features:  0.8387096774193549
Accuracy on test set using 12 features:  0.8387096774193549
Accuracy on test set using 13 features:  0.8387096774193549
Accuracy on test set using 14 features:  0.8387096774193549
Accuracy on test set using 15 features:  0.8387096774193549
Accuracy on test set using 16 features:  0.8387096774193549
Accuracy on test set using 17 features:  0.838709

Accuracy on test set using 139 features:  0.8387096774193549
1 columns provide the highest accuracy at: 83.87 %


In [101]:
lr_model = LogisticRegression()
rfe = RFE(estimator=lr_model, n_features_to_select=5, step=1)
rfe.fit(X_train, y_train)
y_test_hat = rfe.predict(X_test)
print("accuracy score on test set: ", accuracy_score(y_test, y_test_hat))

accuracy score on test set:  0.8387096774193549


In [102]:
relevant_cols = []
for i in range(X_train.shape[1]):
    print('Column: %d, Selected %s, Rank: %.3f' % (i, rfe.support_[i], rfe.ranking_[i]))
    if rfe.support_[i] == True:
        relevant_cols.append(i)
        
print(relevant_cols)

Column: 0, Selected False, Rank: 40.000
Column: 1, Selected False, Rank: 108.000
Column: 2, Selected False, Rank: 85.000
Column: 3, Selected False, Rank: 99.000
Column: 4, Selected False, Rank: 31.000
Column: 5, Selected False, Rank: 9.000
Column: 6, Selected False, Rank: 12.000
Column: 7, Selected False, Rank: 48.000
Column: 8, Selected False, Rank: 93.000
Column: 9, Selected False, Rank: 84.000
Column: 10, Selected False, Rank: 70.000
Column: 11, Selected False, Rank: 71.000
Column: 12, Selected False, Rank: 46.000
Column: 13, Selected False, Rank: 34.000
Column: 14, Selected False, Rank: 38.000
Column: 15, Selected False, Rank: 56.000
Column: 16, Selected False, Rank: 69.000
Column: 17, Selected False, Rank: 58.000
Column: 18, Selected False, Rank: 75.000
Column: 19, Selected False, Rank: 111.000
Column: 20, Selected False, Rank: 129.000
Column: 21, Selected False, Rank: 5.000
Column: 22, Selected False, Rank: 54.000
Column: 23, Selected True, Rank: 1.000
Column: 24, Selected False,

In [103]:
print("Columns that provide the best are:", relevant_cols)
result = pd.DataFrame(test['is_ALP'])
result.columns = ["Actual"]
result.insert(1, "Predicted", rfe.predict(X_test))
result.insert(2, "Pref Percent", test['PreferencePercent'].values)
display(result)

Columns that provide the best are: [23, 92, 124, 126, 134]


Actual  Predicted  Pref Percent
3         0          0         56.26
70        0          0         58.36
92        0          0         53.28
124       0          0         57.52
56        1          0         62.21
134       1          0         54.45
107       0          0         71.83
78        1          0         52.98
128       0          0         53.18
65        1          0         52.80
42        1          0         51.50
123       1          0         55.04
111       0          0         65.36
0         1          0         58.18
136       1          0         64.13
98        1          0         50.19
90        0          0         55.04
114       0          0         64.36
108       0          0         57.53
131       0          0         54.24
101       0          0         72.49
68        0          0         70.48
95        1          0         58.40
119       1          0         56.39
64        1          0         66.30
77        0          0         62.99
71        0          0         53.88
150       0          0         64.58
7         1          0         57.52
103       0          0         55.14
53        0          0         58.60

In [104]:
coefficient_DF = pd.DataFrame(list(map(np.ravel, rfe.estimator_.coef_)), columns=X_train.columns[rfe.support_], index=rfe.estimator_.classes_)
coefficient_DF

HEAP - Bachelor Degree Level  \
0                       0.26231   
1                       0.26231   

   RLHP - Husband, Wife or Partner in a registered marriage  \
0                                           0.180321          
1                                           0.180321          

   RELP - Christianity  RELP - Islam  MDCP - Married in a registered marriage  
0             0.300811     -0.200075                                 0.182068  
1             0.300811     -0.200075                                 0.182068

# 4.3 Fairly Safe LNP (84% Accurate)

## Determinants (All are fairly weak)

- Christianity (0.300811)
- Bachelor Degree Level (0.26231)
- Islam (-0.200075)
- Married in a registered marriage (0.182068)
- Husband, Wife or Partner in a registered marriage (0.180321)

# 4.4 Safe ALP

In [138]:
train, test = train_test_split(adjusted_master, test_size=0.2, random_state=142)
print(train.shape)
print(test.shape)

(120, 152)
(31, 152)


In [139]:
X_train = train.drop(['index', 'LGA','PartyNm', 'PreferencePercent', 'Strength', 'is_ALP', 'is_LNP', 'is_Other', 'is_Marginal',
                     'is_Fairly_Safe_ALP', 'is_Fairly_Safe_LNP', 'is_Safe_ALP', 'is_Safe_LNP', 'is_Strength_Other'], axis=1)
y_train = train['is_Safe_ALP']
X_test = test.drop(['index', 'LGA','PartyNm', 'PreferencePercent', 'Strength', 'is_ALP', 'is_LNP', 'is_Other', 'is_Marginal',
                     'is_Fairly_Safe_ALP', 'is_Fairly_Safe_LNP', 'is_Safe_ALP', 'is_Safe_LNP', 'is_Strength_Other'], axis=1)
y_test = test['is_Safe_ALP']

In [140]:
model = LogisticRegression()
model.fit(X_train, y_train)
y_hat_train = model.predict(X_train)
y_hat_test = model.predict(X_test)
print("Accuracy score on training set: ", accuracy_score(y_train, y_hat_train))
print("Accuracy score on testing set: ", accuracy_score(y_test, y_hat_test))

Accuracy score on training set:  0.8166666666666667
Accuracy score on testing set:  0.9032258064516129


In [141]:
acc_scores = []
for i in range(1,140):
    clf = LogisticRegression()
    rfe = RFE(estimator=clf, n_features_to_select=i)
    
    rfe.fit(X_train, y_train)
    
    y_pred = rfe.predict(X_test)
    acc_score = accuracy_score(y_test, y_pred)
    
    print("Accuracy on test set using", i, "features: ", acc_score)
    
    acc_scores.append(acc_score)

best = acc_scores[0]
best_number_of_columns = 0;
for i in range(len(acc_scores)):
    if acc_scores[i] > best:
        best = acc_scores[i]
        best_number_of_columns = i
        
print(best_number_of_columns + 1, 'columns provide the highest accuracy at: %.2f' % (best*100), "%")

Accuracy on test set using 1 features:  0.9032258064516129
Accuracy on test set using 2 features:  0.9032258064516129
Accuracy on test set using 3 features:  0.9032258064516129
Accuracy on test set using 4 features:  0.9032258064516129
Accuracy on test set using 5 features:  0.9032258064516129
Accuracy on test set using 6 features:  0.9032258064516129
Accuracy on test set using 7 features:  0.9032258064516129
Accuracy on test set using 8 features:  0.9032258064516129
Accuracy on test set using 9 features:  0.9032258064516129
Accuracy on test set using 10 features:  0.9032258064516129
Accuracy on test set using 11 features:  0.9032258064516129
Accuracy on test set using 12 features:  0.9032258064516129
Accuracy on test set using 13 features:  0.9032258064516129
Accuracy on test set using 14 features:  0.9032258064516129
Accuracy on test set using 15 features:  0.9032258064516129
Accuracy on test set using 16 features:  0.9032258064516129
Accuracy on test set using 17 features:  0.903225

In [142]:
lr_model = LogisticRegression()
rfe = RFE(estimator=lr_model, n_features_to_select=5, step=1)
rfe.fit(X_train, y_train)
y_test_hat = rfe.predict(X_test)
print("accuracy score on test set: ", accuracy_score(y_test, y_test_hat))

accuracy score on test set:  0.9032258064516129


In [143]:
relevant_cols = []
for i in range(X_train.shape[1]):
    print('Column: %d, Selected %s, Rank: %.3f' % (i, rfe.support_[i], rfe.ranking_[i]))
    if rfe.support_[i] == True:
        relevant_cols.append(i)
        
print(relevant_cols)

Column: 0, Selected False, Rank: 38.000
Column: 1, Selected False, Rank: 114.000
Column: 2, Selected False, Rank: 68.000
Column: 3, Selected False, Rank: 115.000
Column: 4, Selected False, Rank: 8.000
Column: 5, Selected False, Rank: 6.000
Column: 6, Selected False, Rank: 9.000
Column: 7, Selected False, Rank: 31.000
Column: 8, Selected False, Rank: 109.000
Column: 9, Selected False, Rank: 61.000
Column: 10, Selected False, Rank: 50.000
Column: 11, Selected False, Rank: 39.000
Column: 12, Selected False, Rank: 27.000
Column: 13, Selected False, Rank: 20.000
Column: 14, Selected False, Rank: 25.000
Column: 15, Selected False, Rank: 47.000
Column: 16, Selected False, Rank: 65.000
Column: 17, Selected False, Rank: 73.000
Column: 18, Selected False, Rank: 93.000
Column: 19, Selected False, Rank: 111.000
Column: 20, Selected False, Rank: 131.000
Column: 21, Selected False, Rank: 41.000
Column: 22, Selected False, Rank: 113.000
Column: 23, Selected False, Rank: 86.000
Column: 24, Selected Fa

In [144]:
print("Columns that provide the best are:", relevant_cols)
result = pd.DataFrame(test['is_Safe_ALP'])
result.columns = ["Actual"]
result.insert(1, "Predicted", rfe.predict(X_test))
result.insert(2, "Pref Percent", test['PreferencePercent'].values)
display(result)

Columns that provide the best are: [123, 124, 126, 129, 136]


Actual  Predicted  Pref Percent
3         0          0         56.26
70        0          0         58.36
92        0          0         53.28
124       0          0         57.52
56        1          0         62.21
134       0          0         54.45
107       0          0         71.83
78        0          0         52.98
128       0          0         53.18
65        0          0         52.80
42        0          0         51.50
123       0          0         55.04
111       0          0         65.36
0         0          0         58.18
136       1          0         64.13
98        0          0         50.19
90        0          0         55.04
114       0          0         64.36
108       0          0         57.53
131       0          0         54.24
101       0          0         72.49
68        0          0         70.48
95        0          0         58.40
119       0          0         56.39
64        1          0         66.30
77        0          0         62.99
71        0          0         53.88
150       0          0         64.58
7         0          0         57.52
103       0          0         55.14
53        0          0         58.60

In [112]:
coefficient_DF = pd.DataFrame(list(map(np.ravel, rfe.estimator_.coef_)), columns=X_train.columns[rfe.support_], index=rfe.estimator_.classes_)
coefficient_DF

RELP - Buddhism  RELP - Christianity  RELP - Islam  \
0         0.420441            -0.691813      0.851753   
1         0.420441            -0.691813      0.851753   

   RELP - Secular Beliefs and Other Spiritual Beliefs and No Religious Affiliation  \
0                                          -0.735348                                 
1                                          -0.735348                                 

   MDCP - Not married  
0            0.490631  
1            0.490631

# 4.4) Safe ALP (90% Accurate)

## Strongest Determinants
- Islam (0.851753)
- Not married (0.490631)
- Buddhism (0.420441)

## Negative determinants
- Secular Beliefs and Other Spiritual Beliefs and No Religious Affiliation (-0.735348)
- Christianity (-0.691813)

Interesting how religion is so important in determining whether an electorate is a safe ALP seat or not.

# 4.5) Safe LNP

In [113]:
train, test = train_test_split(adjusted_master, test_size=0.2, random_state=142)
print(train.shape)
print(test.shape)

(120, 152)
(31, 152)


In [114]:
X_train = train.drop(['index', 'LGA','PartyNm', 'PreferencePercent', 'Strength', 'is_ALP', 'is_LNP', 'is_Other', 'is_Marginal',
                     'is_Fairly_Safe_ALP', 'is_Fairly_Safe_LNP', 'is_Safe_ALP', 'is_Safe_LNP', 'is_Strength_Other'], axis=1)
y_train = train['is_Safe_LNP']
X_test = test.drop(['index', 'LGA','PartyNm', 'PreferencePercent', 'Strength', 'is_ALP', 'is_LNP', 'is_Other', 'is_Marginal',
                     'is_Fairly_Safe_ALP', 'is_Fairly_Safe_LNP', 'is_Safe_ALP', 'is_Safe_LNP', 'is_Strength_Other'], axis=1)
y_test = test['is_Safe_LNP']

In [115]:
model = LogisticRegression()
model.fit(X_train, y_train)
y_hat_train = model.predict(X_train)
y_hat_test = model.predict(X_test)
print("Accuracy score on training set: ", accuracy_score(y_train, y_hat_train))
print("Accuracy score on testing set: ", accuracy_score(y_test, y_hat_test))

Accuracy score on training set:  0.725
Accuracy score on testing set:  0.8064516129032258


In [116]:
acc_scores = []
for i in range(1,140):
    clf = LogisticRegression()
    rfe = RFE(estimator=clf, n_features_to_select=i)
    
    rfe.fit(X_train, y_train)
    
    y_pred = rfe.predict(X_test)
    acc_score = accuracy_score(y_test, y_pred)
    
    print("Accuracy on test set using", i, "features: ", acc_score)
    
    acc_scores.append(acc_score)

best = acc_scores[0]
best_number_of_columns = 0;
for i in range(len(acc_scores)):
    if acc_scores[i] > best:
        best = acc_scores[i]
        best_number_of_columns = i
        
print(best_number_of_columns + 1, 'columns provide the highest accuracy at: %.2f' % (best*100), "%")

Accuracy on test set using 1 features:  0.8064516129032258
Accuracy on test set using 2 features:  0.8064516129032258
Accuracy on test set using 3 features:  0.8064516129032258
Accuracy on test set using 4 features:  0.8064516129032258
Accuracy on test set using 5 features:  0.8064516129032258
Accuracy on test set using 6 features:  0.8064516129032258
Accuracy on test set using 7 features:  0.8064516129032258
Accuracy on test set using 8 features:  0.8064516129032258
Accuracy on test set using 9 features:  0.8064516129032258
Accuracy on test set using 10 features:  0.8064516129032258
Accuracy on test set using 11 features:  0.8064516129032258
Accuracy on test set using 12 features:  0.8064516129032258
Accuracy on test set using 13 features:  0.8064516129032258
Accuracy on test set using 14 features:  0.8064516129032258
Accuracy on test set using 15 features:  0.8064516129032258
Accuracy on test set using 16 features:  0.8064516129032258
Accuracy on test set using 17 features:  0.806451

In [122]:
lr_model = LogisticRegression()
rfe = RFE(estimator=lr_model, n_features_to_select=10, step=1)
rfe.fit(X_train, y_train)
y_test_hat = rfe.predict(X_test)
print("accuracy score on test set: ", accuracy_score(y_test, y_test_hat))

accuracy score on test set:  0.8064516129032258


In [123]:
relevant_cols = []
for i in range(X_train.shape[1]):
    print('Column: %d, Selected %s, Rank: %.3f' % (i, rfe.support_[i], rfe.ranking_[i]))
    if rfe.support_[i] == True:
        relevant_cols.append(i)
        
print(relevant_cols)

Column: 0, Selected False, Rank: 30.000
Column: 1, Selected False, Rank: 81.000
Column: 2, Selected False, Rank: 39.000
Column: 3, Selected False, Rank: 76.000
Column: 4, Selected False, Rank: 7.000
Column: 5, Selected True, Rank: 1.000
Column: 6, Selected True, Rank: 1.000
Column: 7, Selected False, Rank: 18.000
Column: 8, Selected False, Rank: 59.000
Column: 9, Selected False, Rank: 72.000
Column: 10, Selected False, Rank: 35.000
Column: 11, Selected False, Rank: 25.000
Column: 12, Selected False, Rank: 22.000
Column: 13, Selected False, Rank: 13.000
Column: 14, Selected False, Rank: 21.000
Column: 15, Selected False, Rank: 28.000
Column: 16, Selected False, Rank: 46.000
Column: 17, Selected False, Rank: 65.000
Column: 18, Selected False, Rank: 88.000
Column: 19, Selected False, Rank: 104.000
Column: 20, Selected False, Rank: 121.000
Column: 21, Selected False, Rank: 6.000
Column: 22, Selected False, Rank: 54.000
Column: 23, Selected True, Rank: 1.000
Column: 24, Selected False, Rank

In [124]:
print("Columns that provide the best are:", relevant_cols)
result = pd.DataFrame(test['is_Safe_LNP'])
result.columns = ["Actual"]
result.insert(1, "Predicted", rfe.predict(X_test))
result.insert(2, "Pref Percent", test['PreferencePercent'].values)
display(result)

Columns that provide the best are: [5, 6, 23, 25, 51, 86, 90, 124, 126, 136]


Actual  Predicted  Pref Percent
3         0          0         56.26
70        0          0         58.36
92        0          0         53.28
124       0          0         57.52
56        0          0         62.21
134       0          0         54.45
107       0          0         71.83
78        0          0         52.98
128       0          0         53.18
65        0          0         52.80
42        0          0         51.50
123       0          0         55.04
111       1          0         65.36
0         0          0         58.18
136       0          0         64.13
98        0          0         50.19
90        0          0         55.04
114       1          0         64.36
108       0          0         57.53
131       0          0         54.24
101       1          0         72.49
68        1          0         70.48
95        0          0         58.40
119       0          0         56.39
64        0          0         66.30
77        1          0         62.99
71        0          0         53.88
150       1          0         64.58
7         0          0         57.52
103       0          0         55.14
53        0          0         58.60

In [125]:
coefficient_DF = pd.DataFrame(list(map(np.ravel, rfe.estimator_.coef_)), columns=X_train.columns[rfe.support_], index=rfe.estimator_.classes_)
coefficient_DF

AGE5P - 25-29 years  AGE5P - 30-34 years  HEAP - Bachelor Degree Level  \
0            -0.380901            -0.375461                     -0.525477   
1            -0.380901            -0.375461                     -0.525477   

   HEAP - Certificate III & IV Level  \
0                           0.465158   
1                           0.465158   

   INDP - Agriculture, Forestry and Fishing  MSTP - Never married  \
0                                  0.384531             -0.738896   
1                                  0.384531             -0.738896   

   MSTP - Married  RELP - Christianity  RELP - Islam  MDCP - Not married  
0        0.500072             1.403129     -0.560254           -0.657768  
1        0.500072             1.403129     -0.560254           -0.657768

# 4.5) Safe LNP Interpretation (81% Accuracy)

## Main determinants
- Christianity (1.438735)
- Married (0.500072)

## Negative determinants
- Never married (-0.772616)
- Not married (-0.675473)
- Islam (-0.571603)
- Bachelor Degree Level (-0.554918)

The change of relatively higher percentages of those with their highest level of education being a Bachelors degree being a positive for Fairly safe LNP seat to a very strong negative for Safe LNP seat is interesting. 

# 4.6) Other Model (strength)

In [126]:
train, test = train_test_split(adjusted_master, test_size=0.2, random_state=142)
print(train.shape)
print(test.shape)

(120, 152)
(31, 152)


In [127]:
X_train = train.drop(['index', 'LGA','PartyNm', 'PreferencePercent', 'Strength', 'is_ALP', 'is_LNP', 'is_Other', 'is_Marginal',
                     'is_Fairly_Safe_ALP', 'is_Fairly_Safe_LNP', 'is_Safe_ALP', 'is_Safe_LNP', 'is_Strength_Other'], axis=1)
y_train = train['is_Strength_Other']
X_test = test.drop(['index', 'LGA','PartyNm', 'PreferencePercent', 'Strength', 'is_ALP', 'is_LNP', 'is_Other', 'is_Marginal',
                     'is_Fairly_Safe_ALP', 'is_Fairly_Safe_LNP', 'is_Safe_ALP', 'is_Safe_LNP', 'is_Strength_Other'], axis=1)
y_test = test['is_Strength_Other']

In [128]:
model = LogisticRegression()
model.fit(X_train, y_train)
y_hat_train = model.predict(X_train)
y_hat_test = model.predict(X_test)
print("Accuracy score on training set: ", accuracy_score(y_train, y_hat_train))
print("Accuracy score on testing set: ", accuracy_score(y_test, y_hat_test))

Accuracy score on training set:  0.975
Accuracy score on testing set:  0.967741935483871


In [129]:
acc_scores = []
for i in range(1,140):
    clf = LogisticRegression()
    rfe = RFE(estimator=clf, n_features_to_select=i)
    
    rfe.fit(X_train, y_train)
    
    y_pred = rfe.predict(X_test)
    acc_score = accuracy_score(y_test, y_pred)
    
    print("Accuracy on test set using", i, "features: ", acc_score)
    
    acc_scores.append(acc_score)

best = acc_scores[0]
best_number_of_columns = 0;
for i in range(len(acc_scores)):
    if acc_scores[i] > best:
        best = acc_scores[i]
        best_number_of_columns = i
        
print(best_number_of_columns + 1, 'columns provide the highest accuracy at: %.2f' % (best*100), "%")

Accuracy on test set using 1 features:  0.967741935483871
Accuracy on test set using 2 features:  0.967741935483871
Accuracy on test set using 3 features:  0.967741935483871
Accuracy on test set using 4 features:  0.967741935483871
Accuracy on test set using 5 features:  0.967741935483871
Accuracy on test set using 6 features:  0.967741935483871
Accuracy on test set using 7 features:  0.967741935483871
Accuracy on test set using 8 features:  0.967741935483871
Accuracy on test set using 9 features:  0.967741935483871
Accuracy on test set using 10 features:  0.967741935483871
Accuracy on test set using 11 features:  0.967741935483871
Accuracy on test set using 12 features:  0.967741935483871
Accuracy on test set using 13 features:  0.967741935483871
Accuracy on test set using 14 features:  0.967741935483871
Accuracy on test set using 15 features:  0.967741935483871
Accuracy on test set using 16 features:  0.967741935483871
Accuracy on test set using 17 features:  0.967741935483871
Accura

In [134]:
lr_model = LogisticRegression()
rfe = RFE(estimator=lr_model, n_features_to_select=5, step=1)
rfe.fit(X_train, y_train)
y_test_hat = rfe.predict(X_test)
print("accuracy score on test set: ", accuracy_score(y_test, y_test_hat))

accuracy score on test set:  0.967741935483871


In [135]:
relevant_cols = []
for i in range(X_train.shape[1]):
    print('Column: %d, Selected %s, Rank: %.3f' % (i, rfe.support_[i], rfe.ranking_[i]))
    if rfe.support_[i] == True:
        relevant_cols.append(i)
        
print(relevant_cols)

Column: 0, Selected False, Rank: 63.000
Column: 1, Selected False, Rank: 72.000
Column: 2, Selected False, Rank: 65.000
Column: 3, Selected False, Rank: 56.000
Column: 4, Selected False, Rank: 29.000
Column: 5, Selected False, Rank: 44.000
Column: 6, Selected False, Rank: 45.000
Column: 7, Selected False, Rank: 97.000
Column: 8, Selected False, Rank: 51.000
Column: 9, Selected False, Rank: 61.000
Column: 10, Selected False, Rank: 59.000
Column: 11, Selected False, Rank: 50.000
Column: 12, Selected False, Rank: 91.000
Column: 13, Selected False, Rank: 101.000
Column: 14, Selected False, Rank: 71.000
Column: 15, Selected False, Rank: 105.000
Column: 16, Selected False, Rank: 129.000
Column: 17, Selected False, Rank: 109.000
Column: 18, Selected False, Rank: 123.000
Column: 19, Selected False, Rank: 130.000
Column: 20, Selected False, Rank: 132.000
Column: 21, Selected False, Rank: 14.000
Column: 22, Selected False, Rank: 70.000
Column: 23, Selected False, Rank: 3.000
Column: 24, Selected

In [136]:
print("Columns that provide the best are:", relevant_cols)
result = pd.DataFrame(test['is_Safe_LNP'])
result.columns = ["Actual"]
result.insert(1, "Predicted", rfe.predict(X_test))
result.insert(2, "Pref Percent", test['PreferencePercent'].values)
display(result)

Columns that provide the best are: [39, 90, 92, 129, 134]


Actual  Predicted  Pref Percent
3         0          0         56.26
70        0          0         58.36
92        0          0         53.28
124       0          0         57.52
56        0          0         62.21
134       0          0         54.45
107       0          0         71.83
78        0          0         52.98
128       0          0         53.18
65        0          0         52.80
42        0          0         51.50
123       0          0         55.04
111       1          0         65.36
0         0          0         58.18
136       0          0         64.13
98        0          0         50.19
90        0          0         55.04
114       1          0         64.36
108       0          0         57.53
131       0          0         54.24
101       1          0         72.49
68        1          0         70.48
95        0          0         58.40
119       0          0         56.39
64        0          0         66.30
77        1          0         62.99
71        0          0         53.88
150       1          0         64.58
7         0          0         57.52
103       0          0         55.14
53        0          0         58.60

In [137]:
coefficient_DF = pd.DataFrame(list(map(np.ravel, rfe.estimator_.coef_)), columns=X_train.columns[rfe.support_], index=rfe.estimator_.classes_)
coefficient_DF

INCP - $3,000 or more ($156,000 or more)  MSTP - Married  \
0                                  0.061699       -0.072724   
1                                  0.061699       -0.072724   

   RLHP - Husband, Wife or Partner in a registered marriage  \
0                                          -0.077377          
1                                          -0.077377          

   RELP - Secular Beliefs and Other Spiritual Beliefs and No Religious Affiliation  \
0                                           0.120757                                 
1                                           0.120757                                 

   MDCP - Married in a registered marriage  
0                                 -0.07698  
1                                 -0.07698

# 4.6 Other Interpretation (97% Accuracy)

## Strongest determinants
- Secular Beliefs and Other Spiritual Beliefs and No Religious Affiliation (0.120757)
- 3,000 or more( 156,000 or more) (0.061699)

## Negative
- Husband, Wife or Partner in a registered marriage (-0.077377)
- Married in a registered marriage (-0.07698)
- Married (-0.072724)

Note, like predicting other in the 3 model for other, the coefficients are all very low/ weak hence even though we supposedly have a 97% accuracy, this is due to having very few data points in this category. Would not use this evidence that other is well predicted for reasons as stated in the 3- model of the other category, they are very similar.  